//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechShopperBO.CarritoItemsWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", ConfigurationName="CarritoItemsWS.CarritoItems")]
    public interface CarritoItems {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/vaciarCarritoRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/vaciarCarritoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.CarritoItemsWS.vaciarCarritoResponse vaciarCarrito(TechShopperBO.CarritoItemsWS.vaciarCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/vaciarCarritoRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/vaciarCarritoResponse")]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.vaciarCarritoResponse> vaciarCarritoAsync(TechShopperBO.CarritoItemsWS.vaciarCarritoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/insertarCarritoItemRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/insertarCarritoItemResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.CarritoItemsWS.insertarCarritoItemResponse insertarCarritoItem(TechShopperBO.CarritoItemsWS.insertarCarritoItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/insertarCarritoItemRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/insertarCarritoItemResponse")]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.insertarCarritoItemResponse> insertarCarritoItemAsync(TechShopperBO.CarritoItemsWS.insertarCarritoItemRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/modificarCarritoItemRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/modificarCarritoItemResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.CarritoItemsWS.modificarCarritoItemResponse modificarCarritoItem(TechShopperBO.CarritoItemsWS.modificarCarritoItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/modificarCarritoItemRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/modificarCarritoItemResponse" +
            "")]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.modificarCarritoItemResponse> modificarCarritoItemAsync(TechShopperBO.CarritoItemsWS.modificarCarritoItemRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/listarTodosLosCarritoItemsRe" +
            "quest", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/listarTodosLosCarritoItemsRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.CarritoItemsWS.listarTodosLosCarritoItemsResponse listarTodosLosCarritoItems(TechShopperBO.CarritoItemsWS.listarTodosLosCarritoItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/listarTodosLosCarritoItemsRe" +
            "quest", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/listarTodosLosCarritoItemsRe" +
            "sponse")]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.listarTodosLosCarritoItemsResponse> listarTodosLosCarritoItemsAsync(TechShopperBO.CarritoItemsWS.listarTodosLosCarritoItemsRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/agregarProductoAlCarritoRequ" +
            "est", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/agregarProductoAlCarritoResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.CarritoItemsWS.agregarProductoAlCarritoResponse agregarProductoAlCarrito(TechShopperBO.CarritoItemsWS.agregarProductoAlCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/agregarProductoAlCarritoRequ" +
            "est", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/agregarProductoAlCarritoResp" +
            "onse")]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.agregarProductoAlCarritoResponse> agregarProductoAlCarritoAsync(TechShopperBO.CarritoItemsWS.agregarProductoAlCarritoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/calcularTotalCarritoRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/calcularTotalCarritoResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.CarritoItemsWS.calcularTotalCarritoResponse calcularTotalCarrito(TechShopperBO.CarritoItemsWS.calcularTotalCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/calcularTotalCarritoRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/calcularTotalCarritoResponse" +
            "")]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.calcularTotalCarritoResponse> calcularTotalCarritoAsync(TechShopperBO.CarritoItemsWS.calcularTotalCarritoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/actualizarCantidadProductoRe" +
            "quest", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/actualizarCantidadProductoRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.CarritoItemsWS.actualizarCantidadProductoResponse actualizarCantidadProducto(TechShopperBO.CarritoItemsWS.actualizarCantidadProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/actualizarCantidadProductoRe" +
            "quest", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/actualizarCantidadProductoRe" +
            "sponse")]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.actualizarCantidadProductoResponse> actualizarCantidadProductoAsync(TechShopperBO.CarritoItemsWS.actualizarCantidadProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/eliminarProductoDelCarritoRe" +
            "quest", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/eliminarProductoDelCarritoRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.CarritoItemsWS.eliminarProductoDelCarritoResponse eliminarProductoDelCarrito(TechShopperBO.CarritoItemsWS.eliminarProductoDelCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/eliminarProductoDelCarritoRe" +
            "quest", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/eliminarProductoDelCarritoRe" +
            "sponse")]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.eliminarProductoDelCarritoResponse> eliminarProductoDelCarritoAsync(TechShopperBO.CarritoItemsWS.eliminarProductoDelCarritoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/listarItemsPorCarritoRequest" +
            "", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/listarItemsPorCarritoRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.CarritoItemsWS.listarItemsPorCarritoResponse listarItemsPorCarrito(TechShopperBO.CarritoItemsWS.listarItemsPorCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/listarItemsPorCarritoRequest" +
            "", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/listarItemsPorCarritoRespons" +
            "e")]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.listarItemsPorCarritoResponse> listarItemsPorCarritoAsync(TechShopperBO.CarritoItemsWS.listarItemsPorCarritoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/eliminarCarritoItemRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/eliminarCarritoItemResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.CarritoItemsWS.eliminarCarritoItemResponse eliminarCarritoItem(TechShopperBO.CarritoItemsWS.eliminarCarritoItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/eliminarCarritoItemRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/eliminarCarritoItemResponse")]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.eliminarCarritoItemResponse> eliminarCarritoItemAsync(TechShopperBO.CarritoItemsWS.eliminarCarritoItemRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/obtenerCarritoItemPorIdReque" +
            "st", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/obtenerCarritoItemPorIdRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.CarritoItemsWS.obtenerCarritoItemPorIdResponse obtenerCarritoItemPorId(TechShopperBO.CarritoItemsWS.obtenerCarritoItemPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/CarritoItems/obtenerCarritoItemPorIdReque" +
            "st", ReplyAction="http://services.techshopper.pucp.edu.pe/CarritoItems/obtenerCarritoItemPorIdRespo" +
            "nse")]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.obtenerCarritoItemPorIdResponse> obtenerCarritoItemPorIdAsync(TechShopperBO.CarritoItemsWS.obtenerCarritoItemPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="vaciarCarrito", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class vaciarCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCarrito;
        
        public vaciarCarritoRequest() {
        }
        
        public vaciarCarritoRequest(int idCarrito) {
            this.idCarrito = idCarrito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="vaciarCarritoResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class vaciarCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public vaciarCarritoResponse() {
        }
        
        public vaciarCarritoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class localDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class productoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private categoriaDTO categoriaField;
        
        private bool categoriaFieldSpecified;
        
        private string descripcionField;
        
        private int idProductoField;
        
        private bool idProductoFieldSpecified;
        
        private string imagenURLField;
        
        private string marcaField;
        
        private string nombreField;
        
        private double precioField;
        
        private bool precioFieldSpecified;
        
        private int stockDisponibleField;
        
        private bool stockDisponibleFieldSpecified;
        
        private int stockMinimoField;
        
        private bool stockMinimoFieldSpecified;
        
        private int stockReservadoField;
        
        private bool stockReservadoFieldSpecified;
        
        private usuarioDTO usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaDTO categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaSpecified {
            get {
                return this.categoriaFieldSpecified;
            }
            set {
                this.categoriaFieldSpecified = value;
                this.RaisePropertyChanged("categoriaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoSpecified {
            get {
                return this.idProductoFieldSpecified;
            }
            set {
                this.idProductoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string imagenURL {
            get {
                return this.imagenURLField;
            }
            set {
                this.imagenURLField = value;
                this.RaisePropertyChanged("imagenURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioSpecified {
            get {
                return this.precioFieldSpecified;
            }
            set {
                this.precioFieldSpecified = value;
                this.RaisePropertyChanged("precioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int stockDisponible {
            get {
                return this.stockDisponibleField;
            }
            set {
                this.stockDisponibleField = value;
                this.RaisePropertyChanged("stockDisponible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockDisponibleSpecified {
            get {
                return this.stockDisponibleFieldSpecified;
            }
            set {
                this.stockDisponibleFieldSpecified = value;
                this.RaisePropertyChanged("stockDisponibleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int stockMinimo {
            get {
                return this.stockMinimoField;
            }
            set {
                this.stockMinimoField = value;
                this.RaisePropertyChanged("stockMinimo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockMinimoSpecified {
            get {
                return this.stockMinimoFieldSpecified;
            }
            set {
                this.stockMinimoFieldSpecified = value;
                this.RaisePropertyChanged("stockMinimoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int stockReservado {
            get {
                return this.stockReservadoField;
            }
            set {
                this.stockReservadoField = value;
                this.RaisePropertyChanged("stockReservado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockReservadoSpecified {
            get {
                return this.stockReservadoFieldSpecified;
            }
            set {
                this.stockReservadoFieldSpecified = value;
                this.RaisePropertyChanged("stockReservadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public usuarioDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public enum categoriaDTO {
        
        /// <remarks/>
        LAPTOP,
        
        /// <remarks/>
        PC,
        
        /// <remarks/>
        MOUSE,
        
        /// <remarks/>
        MONITOR,
        
        /// <remarks/>
        TECLADO,
        
        /// <remarks/>
        AURICULARES,
        
        /// <remarks/>
        AUDIFONOS,
        
        /// <remarks/>
        MICROFONO,
        
        /// <remarks/>
        PARLANTES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contraseñaField;
        
        private string emailField;
        
        private estadoConexionDTO estadoConexionField;
        
        private bool estadoConexionFieldSpecified;
        
        private localDateTime fechaRegistroField;
        
        private int idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string nombreField;
        
        private rolUsuarioDTO rolField;
        
        private bool rolFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoConexionDTO estadoConexion {
            get {
                return this.estadoConexionField;
            }
            set {
                this.estadoConexionField = value;
                this.RaisePropertyChanged("estadoConexion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoConexionSpecified {
            get {
                return this.estadoConexionFieldSpecified;
            }
            set {
                this.estadoConexionFieldSpecified = value;
                this.RaisePropertyChanged("estadoConexionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public rolUsuarioDTO rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rolSpecified {
            get {
                return this.rolFieldSpecified;
            }
            set {
                this.rolFieldSpecified = value;
                this.RaisePropertyChanged("rolSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public enum estadoConexionDTO {
        
        /// <remarks/>
        CONECTADO,
        
        /// <remarks/>
        DESCONECTADO,
        
        /// <remarks/>
        EN_eSPERA,
        
        /// <remarks/>
        RECONECTADO,
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        LIMITADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public enum rolUsuarioDTO {
        
        /// <remarks/>
        CLIENTE,
        
        /// <remarks/>
        ADMINISTRADOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class carritoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idCarritoField;
        
        private bool idCarritoFieldSpecified;
        
        private double precioField;
        
        private bool precioFieldSpecified;
        
        private usuarioDTO usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idCarrito {
            get {
                return this.idCarritoField;
            }
            set {
                this.idCarritoField = value;
                this.RaisePropertyChanged("idCarrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCarritoSpecified {
            get {
                return this.idCarritoFieldSpecified;
            }
            set {
                this.idCarritoFieldSpecified = value;
                this.RaisePropertyChanged("idCarritoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioSpecified {
            get {
                return this.precioFieldSpecified;
            }
            set {
                this.precioFieldSpecified = value;
                this.RaisePropertyChanged("precioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public usuarioDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class carritoItemsDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private carritoDTO carritoField;
        
        private localDateTime fechaRegistroField;
        
        private double precioUnitarioField;
        
        private productoDTO productoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public carritoDTO carrito {
            get {
                return this.carritoField;
            }
            set {
                this.carritoField = value;
                this.RaisePropertyChanged("carrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public localDateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("precioUnitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public productoDTO producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCarritoItem", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCarritoItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCarrito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precioUnitario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperBO.CarritoItemsWS.localDateTime fechaRegistro;
        
        public insertarCarritoItemRequest() {
        }
        
        public insertarCarritoItemRequest(int idCarrito, int idProducto, int cantidad, double precioUnitario, TechShopperBO.CarritoItemsWS.localDateTime fechaRegistro) {
            this.idCarrito = idCarrito;
            this.idProducto = idProducto;
            this.cantidad = cantidad;
            this.precioUnitario = precioUnitario;
            this.fechaRegistro = fechaRegistro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCarritoItemResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCarritoItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarCarritoItemResponse() {
        }
        
        public insertarCarritoItemResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCarritoItem", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCarritoItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCarritoItem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCarrito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precioUnitario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperBO.CarritoItemsWS.localDateTime fechaRegistro;
        
        public modificarCarritoItemRequest() {
        }
        
        public modificarCarritoItemRequest(int idCarritoItem, int idCarrito, int idProducto, int cantidad, double precioUnitario, TechShopperBO.CarritoItemsWS.localDateTime fechaRegistro) {
            this.idCarritoItem = idCarritoItem;
            this.idCarrito = idCarrito;
            this.idProducto = idProducto;
            this.cantidad = cantidad;
            this.precioUnitario = precioUnitario;
            this.fechaRegistro = fechaRegistro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCarritoItemResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCarritoItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarCarritoItemResponse() {
        }
        
        public modificarCarritoItemResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosLosCarritoItems", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosLosCarritoItemsRequest {
        
        public listarTodosLosCarritoItemsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosLosCarritoItemsResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosLosCarritoItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperBO.CarritoItemsWS.carritoItemsDTO[] @return;
        
        public listarTodosLosCarritoItemsResponse() {
        }
        
        public listarTodosLosCarritoItemsResponse(TechShopperBO.CarritoItemsWS.carritoItemsDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarProductoAlCarrito", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class agregarProductoAlCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCarrito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precioUnitario;
        
        public agregarProductoAlCarritoRequest() {
        }
        
        public agregarProductoAlCarritoRequest(int idCarrito, int idProducto, int cantidad, double precioUnitario) {
            this.idCarrito = idCarrito;
            this.idProducto = idProducto;
            this.cantidad = cantidad;
            this.precioUnitario = precioUnitario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarProductoAlCarritoResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class agregarProductoAlCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public agregarProductoAlCarritoResponse() {
        }
        
        public agregarProductoAlCarritoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="calcularTotalCarrito", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class calcularTotalCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCarrito;
        
        public calcularTotalCarritoRequest() {
        }
        
        public calcularTotalCarritoRequest(int idCarrito) {
            this.idCarrito = idCarrito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="calcularTotalCarritoResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class calcularTotalCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public calcularTotalCarritoResponse() {
        }
        
        public calcularTotalCarritoResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarCantidadProducto", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarCantidadProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCarrito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int nuevaCantidad;
        
        public actualizarCantidadProductoRequest() {
        }
        
        public actualizarCantidadProductoRequest(int idCarrito, int idProducto, int nuevaCantidad) {
            this.idCarrito = idCarrito;
            this.idProducto = idProducto;
            this.nuevaCantidad = nuevaCantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarCantidadProductoResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarCantidadProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarCantidadProductoResponse() {
        }
        
        public actualizarCantidadProductoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProductoDelCarrito", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarProductoDelCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCarrito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        public eliminarProductoDelCarritoRequest() {
        }
        
        public eliminarProductoDelCarritoRequest(int idCarrito, int idProducto) {
            this.idCarrito = idCarrito;
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProductoDelCarritoResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarProductoDelCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarProductoDelCarritoResponse() {
        }
        
        public eliminarProductoDelCarritoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarItemsPorCarrito", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarItemsPorCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCarrito;
        
        public listarItemsPorCarritoRequest() {
        }
        
        public listarItemsPorCarritoRequest(int idCarrito) {
            this.idCarrito = idCarrito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarItemsPorCarritoResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarItemsPorCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperBO.CarritoItemsWS.carritoItemsDTO[] @return;
        
        public listarItemsPorCarritoResponse() {
        }
        
        public listarItemsPorCarritoResponse(TechShopperBO.CarritoItemsWS.carritoItemsDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCarritoItem", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCarritoItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCarritoItem;
        
        public eliminarCarritoItemRequest() {
        }
        
        public eliminarCarritoItemRequest(int idCarritoItem) {
            this.idCarritoItem = idCarritoItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCarritoItemResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCarritoItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarCarritoItemResponse() {
        }
        
        public eliminarCarritoItemResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCarritoItemPorId", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCarritoItemPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCarritoItem;
        
        public obtenerCarritoItemPorIdRequest() {
        }
        
        public obtenerCarritoItemPorIdRequest(int idCarritoItem) {
            this.idCarritoItem = idCarritoItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCarritoItemPorIdResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCarritoItemPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperBO.CarritoItemsWS.carritoItemsDTO @return;
        
        public obtenerCarritoItemPorIdResponse() {
        }
        
        public obtenerCarritoItemPorIdResponse(TechShopperBO.CarritoItemsWS.carritoItemsDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CarritoItemsChannel : TechShopperBO.CarritoItemsWS.CarritoItems, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarritoItemsClient : System.ServiceModel.ClientBase<TechShopperBO.CarritoItemsWS.CarritoItems>, TechShopperBO.CarritoItemsWS.CarritoItems {
        
        public CarritoItemsClient() {
        }
        
        public CarritoItemsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarritoItemsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarritoItemsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarritoItemsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.CarritoItemsWS.vaciarCarritoResponse TechShopperBO.CarritoItemsWS.CarritoItems.vaciarCarrito(TechShopperBO.CarritoItemsWS.vaciarCarritoRequest request) {
            return base.Channel.vaciarCarrito(request);
        }
        
        public int vaciarCarrito(int idCarrito) {
            TechShopperBO.CarritoItemsWS.vaciarCarritoRequest inValue = new TechShopperBO.CarritoItemsWS.vaciarCarritoRequest();
            inValue.idCarrito = idCarrito;
            TechShopperBO.CarritoItemsWS.vaciarCarritoResponse retVal = ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).vaciarCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.vaciarCarritoResponse> TechShopperBO.CarritoItemsWS.CarritoItems.vaciarCarritoAsync(TechShopperBO.CarritoItemsWS.vaciarCarritoRequest request) {
            return base.Channel.vaciarCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.vaciarCarritoResponse> vaciarCarritoAsync(int idCarrito) {
            TechShopperBO.CarritoItemsWS.vaciarCarritoRequest inValue = new TechShopperBO.CarritoItemsWS.vaciarCarritoRequest();
            inValue.idCarrito = idCarrito;
            return ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).vaciarCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.CarritoItemsWS.insertarCarritoItemResponse TechShopperBO.CarritoItemsWS.CarritoItems.insertarCarritoItem(TechShopperBO.CarritoItemsWS.insertarCarritoItemRequest request) {
            return base.Channel.insertarCarritoItem(request);
        }
        
        public int insertarCarritoItem(int idCarrito, int idProducto, int cantidad, double precioUnitario, TechShopperBO.CarritoItemsWS.localDateTime fechaRegistro) {
            TechShopperBO.CarritoItemsWS.insertarCarritoItemRequest inValue = new TechShopperBO.CarritoItemsWS.insertarCarritoItemRequest();
            inValue.idCarrito = idCarrito;
            inValue.idProducto = idProducto;
            inValue.cantidad = cantidad;
            inValue.precioUnitario = precioUnitario;
            inValue.fechaRegistro = fechaRegistro;
            TechShopperBO.CarritoItemsWS.insertarCarritoItemResponse retVal = ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).insertarCarritoItem(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.insertarCarritoItemResponse> TechShopperBO.CarritoItemsWS.CarritoItems.insertarCarritoItemAsync(TechShopperBO.CarritoItemsWS.insertarCarritoItemRequest request) {
            return base.Channel.insertarCarritoItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.insertarCarritoItemResponse> insertarCarritoItemAsync(int idCarrito, int idProducto, int cantidad, double precioUnitario, TechShopperBO.CarritoItemsWS.localDateTime fechaRegistro) {
            TechShopperBO.CarritoItemsWS.insertarCarritoItemRequest inValue = new TechShopperBO.CarritoItemsWS.insertarCarritoItemRequest();
            inValue.idCarrito = idCarrito;
            inValue.idProducto = idProducto;
            inValue.cantidad = cantidad;
            inValue.precioUnitario = precioUnitario;
            inValue.fechaRegistro = fechaRegistro;
            return ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).insertarCarritoItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.CarritoItemsWS.modificarCarritoItemResponse TechShopperBO.CarritoItemsWS.CarritoItems.modificarCarritoItem(TechShopperBO.CarritoItemsWS.modificarCarritoItemRequest request) {
            return base.Channel.modificarCarritoItem(request);
        }
        
        public int modificarCarritoItem(int idCarritoItem, int idCarrito, int idProducto, int cantidad, double precioUnitario, TechShopperBO.CarritoItemsWS.localDateTime fechaRegistro) {
            TechShopperBO.CarritoItemsWS.modificarCarritoItemRequest inValue = new TechShopperBO.CarritoItemsWS.modificarCarritoItemRequest();
            inValue.idCarritoItem = idCarritoItem;
            inValue.idCarrito = idCarrito;
            inValue.idProducto = idProducto;
            inValue.cantidad = cantidad;
            inValue.precioUnitario = precioUnitario;
            inValue.fechaRegistro = fechaRegistro;
            TechShopperBO.CarritoItemsWS.modificarCarritoItemResponse retVal = ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).modificarCarritoItem(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.modificarCarritoItemResponse> TechShopperBO.CarritoItemsWS.CarritoItems.modificarCarritoItemAsync(TechShopperBO.CarritoItemsWS.modificarCarritoItemRequest request) {
            return base.Channel.modificarCarritoItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.modificarCarritoItemResponse> modificarCarritoItemAsync(int idCarritoItem, int idCarrito, int idProducto, int cantidad, double precioUnitario, TechShopperBO.CarritoItemsWS.localDateTime fechaRegistro) {
            TechShopperBO.CarritoItemsWS.modificarCarritoItemRequest inValue = new TechShopperBO.CarritoItemsWS.modificarCarritoItemRequest();
            inValue.idCarritoItem = idCarritoItem;
            inValue.idCarrito = idCarrito;
            inValue.idProducto = idProducto;
            inValue.cantidad = cantidad;
            inValue.precioUnitario = precioUnitario;
            inValue.fechaRegistro = fechaRegistro;
            return ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).modificarCarritoItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.CarritoItemsWS.listarTodosLosCarritoItemsResponse TechShopperBO.CarritoItemsWS.CarritoItems.listarTodosLosCarritoItems(TechShopperBO.CarritoItemsWS.listarTodosLosCarritoItemsRequest request) {
            return base.Channel.listarTodosLosCarritoItems(request);
        }
        
        public TechShopperBO.CarritoItemsWS.carritoItemsDTO[] listarTodosLosCarritoItems() {
            TechShopperBO.CarritoItemsWS.listarTodosLosCarritoItemsRequest inValue = new TechShopperBO.CarritoItemsWS.listarTodosLosCarritoItemsRequest();
            TechShopperBO.CarritoItemsWS.listarTodosLosCarritoItemsResponse retVal = ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).listarTodosLosCarritoItems(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.listarTodosLosCarritoItemsResponse> TechShopperBO.CarritoItemsWS.CarritoItems.listarTodosLosCarritoItemsAsync(TechShopperBO.CarritoItemsWS.listarTodosLosCarritoItemsRequest request) {
            return base.Channel.listarTodosLosCarritoItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.listarTodosLosCarritoItemsResponse> listarTodosLosCarritoItemsAsync() {
            TechShopperBO.CarritoItemsWS.listarTodosLosCarritoItemsRequest inValue = new TechShopperBO.CarritoItemsWS.listarTodosLosCarritoItemsRequest();
            return ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).listarTodosLosCarritoItemsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.CarritoItemsWS.agregarProductoAlCarritoResponse TechShopperBO.CarritoItemsWS.CarritoItems.agregarProductoAlCarrito(TechShopperBO.CarritoItemsWS.agregarProductoAlCarritoRequest request) {
            return base.Channel.agregarProductoAlCarrito(request);
        }
        
        public int agregarProductoAlCarrito(int idCarrito, int idProducto, int cantidad, double precioUnitario) {
            TechShopperBO.CarritoItemsWS.agregarProductoAlCarritoRequest inValue = new TechShopperBO.CarritoItemsWS.agregarProductoAlCarritoRequest();
            inValue.idCarrito = idCarrito;
            inValue.idProducto = idProducto;
            inValue.cantidad = cantidad;
            inValue.precioUnitario = precioUnitario;
            TechShopperBO.CarritoItemsWS.agregarProductoAlCarritoResponse retVal = ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).agregarProductoAlCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.agregarProductoAlCarritoResponse> TechShopperBO.CarritoItemsWS.CarritoItems.agregarProductoAlCarritoAsync(TechShopperBO.CarritoItemsWS.agregarProductoAlCarritoRequest request) {
            return base.Channel.agregarProductoAlCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.agregarProductoAlCarritoResponse> agregarProductoAlCarritoAsync(int idCarrito, int idProducto, int cantidad, double precioUnitario) {
            TechShopperBO.CarritoItemsWS.agregarProductoAlCarritoRequest inValue = new TechShopperBO.CarritoItemsWS.agregarProductoAlCarritoRequest();
            inValue.idCarrito = idCarrito;
            inValue.idProducto = idProducto;
            inValue.cantidad = cantidad;
            inValue.precioUnitario = precioUnitario;
            return ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).agregarProductoAlCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.CarritoItemsWS.calcularTotalCarritoResponse TechShopperBO.CarritoItemsWS.CarritoItems.calcularTotalCarrito(TechShopperBO.CarritoItemsWS.calcularTotalCarritoRequest request) {
            return base.Channel.calcularTotalCarrito(request);
        }
        
        public double calcularTotalCarrito(int idCarrito) {
            TechShopperBO.CarritoItemsWS.calcularTotalCarritoRequest inValue = new TechShopperBO.CarritoItemsWS.calcularTotalCarritoRequest();
            inValue.idCarrito = idCarrito;
            TechShopperBO.CarritoItemsWS.calcularTotalCarritoResponse retVal = ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).calcularTotalCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.calcularTotalCarritoResponse> TechShopperBO.CarritoItemsWS.CarritoItems.calcularTotalCarritoAsync(TechShopperBO.CarritoItemsWS.calcularTotalCarritoRequest request) {
            return base.Channel.calcularTotalCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.calcularTotalCarritoResponse> calcularTotalCarritoAsync(int idCarrito) {
            TechShopperBO.CarritoItemsWS.calcularTotalCarritoRequest inValue = new TechShopperBO.CarritoItemsWS.calcularTotalCarritoRequest();
            inValue.idCarrito = idCarrito;
            return ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).calcularTotalCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.CarritoItemsWS.actualizarCantidadProductoResponse TechShopperBO.CarritoItemsWS.CarritoItems.actualizarCantidadProducto(TechShopperBO.CarritoItemsWS.actualizarCantidadProductoRequest request) {
            return base.Channel.actualizarCantidadProducto(request);
        }
        
        public int actualizarCantidadProducto(int idCarrito, int idProducto, int nuevaCantidad) {
            TechShopperBO.CarritoItemsWS.actualizarCantidadProductoRequest inValue = new TechShopperBO.CarritoItemsWS.actualizarCantidadProductoRequest();
            inValue.idCarrito = idCarrito;
            inValue.idProducto = idProducto;
            inValue.nuevaCantidad = nuevaCantidad;
            TechShopperBO.CarritoItemsWS.actualizarCantidadProductoResponse retVal = ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).actualizarCantidadProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.actualizarCantidadProductoResponse> TechShopperBO.CarritoItemsWS.CarritoItems.actualizarCantidadProductoAsync(TechShopperBO.CarritoItemsWS.actualizarCantidadProductoRequest request) {
            return base.Channel.actualizarCantidadProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.actualizarCantidadProductoResponse> actualizarCantidadProductoAsync(int idCarrito, int idProducto, int nuevaCantidad) {
            TechShopperBO.CarritoItemsWS.actualizarCantidadProductoRequest inValue = new TechShopperBO.CarritoItemsWS.actualizarCantidadProductoRequest();
            inValue.idCarrito = idCarrito;
            inValue.idProducto = idProducto;
            inValue.nuevaCantidad = nuevaCantidad;
            return ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).actualizarCantidadProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.CarritoItemsWS.eliminarProductoDelCarritoResponse TechShopperBO.CarritoItemsWS.CarritoItems.eliminarProductoDelCarrito(TechShopperBO.CarritoItemsWS.eliminarProductoDelCarritoRequest request) {
            return base.Channel.eliminarProductoDelCarrito(request);
        }
        
        public int eliminarProductoDelCarrito(int idCarrito, int idProducto) {
            TechShopperBO.CarritoItemsWS.eliminarProductoDelCarritoRequest inValue = new TechShopperBO.CarritoItemsWS.eliminarProductoDelCarritoRequest();
            inValue.idCarrito = idCarrito;
            inValue.idProducto = idProducto;
            TechShopperBO.CarritoItemsWS.eliminarProductoDelCarritoResponse retVal = ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).eliminarProductoDelCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.eliminarProductoDelCarritoResponse> TechShopperBO.CarritoItemsWS.CarritoItems.eliminarProductoDelCarritoAsync(TechShopperBO.CarritoItemsWS.eliminarProductoDelCarritoRequest request) {
            return base.Channel.eliminarProductoDelCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.eliminarProductoDelCarritoResponse> eliminarProductoDelCarritoAsync(int idCarrito, int idProducto) {
            TechShopperBO.CarritoItemsWS.eliminarProductoDelCarritoRequest inValue = new TechShopperBO.CarritoItemsWS.eliminarProductoDelCarritoRequest();
            inValue.idCarrito = idCarrito;
            inValue.idProducto = idProducto;
            return ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).eliminarProductoDelCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.CarritoItemsWS.listarItemsPorCarritoResponse TechShopperBO.CarritoItemsWS.CarritoItems.listarItemsPorCarrito(TechShopperBO.CarritoItemsWS.listarItemsPorCarritoRequest request) {
            return base.Channel.listarItemsPorCarrito(request);
        }
        
        public TechShopperBO.CarritoItemsWS.carritoItemsDTO[] listarItemsPorCarrito(int idCarrito) {
            TechShopperBO.CarritoItemsWS.listarItemsPorCarritoRequest inValue = new TechShopperBO.CarritoItemsWS.listarItemsPorCarritoRequest();
            inValue.idCarrito = idCarrito;
            TechShopperBO.CarritoItemsWS.listarItemsPorCarritoResponse retVal = ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).listarItemsPorCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.listarItemsPorCarritoResponse> TechShopperBO.CarritoItemsWS.CarritoItems.listarItemsPorCarritoAsync(TechShopperBO.CarritoItemsWS.listarItemsPorCarritoRequest request) {
            return base.Channel.listarItemsPorCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.listarItemsPorCarritoResponse> listarItemsPorCarritoAsync(int idCarrito) {
            TechShopperBO.CarritoItemsWS.listarItemsPorCarritoRequest inValue = new TechShopperBO.CarritoItemsWS.listarItemsPorCarritoRequest();
            inValue.idCarrito = idCarrito;
            return ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).listarItemsPorCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.CarritoItemsWS.eliminarCarritoItemResponse TechShopperBO.CarritoItemsWS.CarritoItems.eliminarCarritoItem(TechShopperBO.CarritoItemsWS.eliminarCarritoItemRequest request) {
            return base.Channel.eliminarCarritoItem(request);
        }
        
        public int eliminarCarritoItem(int idCarritoItem) {
            TechShopperBO.CarritoItemsWS.eliminarCarritoItemRequest inValue = new TechShopperBO.CarritoItemsWS.eliminarCarritoItemRequest();
            inValue.idCarritoItem = idCarritoItem;
            TechShopperBO.CarritoItemsWS.eliminarCarritoItemResponse retVal = ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).eliminarCarritoItem(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.eliminarCarritoItemResponse> TechShopperBO.CarritoItemsWS.CarritoItems.eliminarCarritoItemAsync(TechShopperBO.CarritoItemsWS.eliminarCarritoItemRequest request) {
            return base.Channel.eliminarCarritoItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.eliminarCarritoItemResponse> eliminarCarritoItemAsync(int idCarritoItem) {
            TechShopperBO.CarritoItemsWS.eliminarCarritoItemRequest inValue = new TechShopperBO.CarritoItemsWS.eliminarCarritoItemRequest();
            inValue.idCarritoItem = idCarritoItem;
            return ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).eliminarCarritoItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.CarritoItemsWS.obtenerCarritoItemPorIdResponse TechShopperBO.CarritoItemsWS.CarritoItems.obtenerCarritoItemPorId(TechShopperBO.CarritoItemsWS.obtenerCarritoItemPorIdRequest request) {
            return base.Channel.obtenerCarritoItemPorId(request);
        }
        
        public TechShopperBO.CarritoItemsWS.carritoItemsDTO obtenerCarritoItemPorId(int idCarritoItem) {
            TechShopperBO.CarritoItemsWS.obtenerCarritoItemPorIdRequest inValue = new TechShopperBO.CarritoItemsWS.obtenerCarritoItemPorIdRequest();
            inValue.idCarritoItem = idCarritoItem;
            TechShopperBO.CarritoItemsWS.obtenerCarritoItemPorIdResponse retVal = ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).obtenerCarritoItemPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.obtenerCarritoItemPorIdResponse> TechShopperBO.CarritoItemsWS.CarritoItems.obtenerCarritoItemPorIdAsync(TechShopperBO.CarritoItemsWS.obtenerCarritoItemPorIdRequest request) {
            return base.Channel.obtenerCarritoItemPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.CarritoItemsWS.obtenerCarritoItemPorIdResponse> obtenerCarritoItemPorIdAsync(int idCarritoItem) {
            TechShopperBO.CarritoItemsWS.obtenerCarritoItemPorIdRequest inValue = new TechShopperBO.CarritoItemsWS.obtenerCarritoItemPorIdRequest();
            inValue.idCarritoItem = idCarritoItem;
            return ((TechShopperBO.CarritoItemsWS.CarritoItems)(this)).obtenerCarritoItemPorIdAsync(inValue);
        }
    }
}
