//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechShopperBO.LocalizacionesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", ConfigurationName="LocalizacionesWS.Localizaciones")]
    public interface Localizaciones {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Localizaciones/insertarLocalizacionReques" +
            "t", ReplyAction="http://services.techshopper.pucp.edu.pe/Localizaciones/insertarLocalizacionRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.LocalizacionesWS.insertarLocalizacionResponse insertarLocalizacion(TechShopperBO.LocalizacionesWS.insertarLocalizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Localizaciones/insertarLocalizacionReques" +
            "t", ReplyAction="http://services.techshopper.pucp.edu.pe/Localizaciones/insertarLocalizacionRespon" +
            "se")]
        System.Threading.Tasks.Task<TechShopperBO.LocalizacionesWS.insertarLocalizacionResponse> insertarLocalizacionAsync(TechShopperBO.LocalizacionesWS.insertarLocalizacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Localizaciones/obtenerLocalizacionPorIdRe" +
            "quest", ReplyAction="http://services.techshopper.pucp.edu.pe/Localizaciones/obtenerLocalizacionPorIdRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.LocalizacionesWS.obtenerLocalizacionPorIdResponse obtenerLocalizacionPorId(TechShopperBO.LocalizacionesWS.obtenerLocalizacionPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Localizaciones/obtenerLocalizacionPorIdRe" +
            "quest", ReplyAction="http://services.techshopper.pucp.edu.pe/Localizaciones/obtenerLocalizacionPorIdRe" +
            "sponse")]
        System.Threading.Tasks.Task<TechShopperBO.LocalizacionesWS.obtenerLocalizacionPorIdResponse> obtenerLocalizacionPorIdAsync(TechShopperBO.LocalizacionesWS.obtenerLocalizacionPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Localizaciones/actualizarLocalizacionRequ" +
            "est", ReplyAction="http://services.techshopper.pucp.edu.pe/Localizaciones/actualizarLocalizacionResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.LocalizacionesWS.actualizarLocalizacionResponse actualizarLocalizacion(TechShopperBO.LocalizacionesWS.actualizarLocalizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Localizaciones/actualizarLocalizacionRequ" +
            "est", ReplyAction="http://services.techshopper.pucp.edu.pe/Localizaciones/actualizarLocalizacionResp" +
            "onse")]
        System.Threading.Tasks.Task<TechShopperBO.LocalizacionesWS.actualizarLocalizacionResponse> actualizarLocalizacionAsync(TechShopperBO.LocalizacionesWS.actualizarLocalizacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Localizaciones/eliminarLocalizacionReques" +
            "t", ReplyAction="http://services.techshopper.pucp.edu.pe/Localizaciones/eliminarLocalizacionRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.LocalizacionesWS.eliminarLocalizacionResponse eliminarLocalizacion(TechShopperBO.LocalizacionesWS.eliminarLocalizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Localizaciones/eliminarLocalizacionReques" +
            "t", ReplyAction="http://services.techshopper.pucp.edu.pe/Localizaciones/eliminarLocalizacionRespon" +
            "se")]
        System.Threading.Tasks.Task<TechShopperBO.LocalizacionesWS.eliminarLocalizacionResponse> eliminarLocalizacionAsync(TechShopperBO.LocalizacionesWS.eliminarLocalizacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Localizaciones/listarTodasLasLocalizacion" +
            "esRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Localizaciones/listarTodasLasLocalizacion" +
            "esResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.LocalizacionesWS.listarTodasLasLocalizacionesResponse listarTodasLasLocalizaciones(TechShopperBO.LocalizacionesWS.listarTodasLasLocalizacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Localizaciones/listarTodasLasLocalizacion" +
            "esRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Localizaciones/listarTodasLasLocalizacion" +
            "esResponse")]
        System.Threading.Tasks.Task<TechShopperBO.LocalizacionesWS.listarTodasLasLocalizacionesResponse> listarTodasLasLocalizacionesAsync(TechShopperBO.LocalizacionesWS.listarTodasLasLocalizacionesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarLocalizacion", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarLocalizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double latitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double longitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public insertarLocalizacionRequest() {
        }
        
        public insertarLocalizacionRequest(string direccion, double latitud, double longitud, int idUsuario) {
            this.direccion = direccion;
            this.latitud = latitud;
            this.longitud = longitud;
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarLocalizacionResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarLocalizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarLocalizacionResponse() {
        }
        
        public insertarLocalizacionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class localizacionDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string direccionField;
        
        private int idLocalizacionField;
        
        private bool idLocalizacionFieldSpecified;
        
        private double latitudField;
        
        private bool latitudFieldSpecified;
        
        private double longitudField;
        
        private bool longitudFieldSpecified;
        
        private usuarioDTO usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idLocalizacion {
            get {
                return this.idLocalizacionField;
            }
            set {
                this.idLocalizacionField = value;
                this.RaisePropertyChanged("idLocalizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idLocalizacionSpecified {
            get {
                return this.idLocalizacionFieldSpecified;
            }
            set {
                this.idLocalizacionFieldSpecified = value;
                this.RaisePropertyChanged("idLocalizacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
                this.RaisePropertyChanged("latitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool latitudSpecified {
            get {
                return this.latitudFieldSpecified;
            }
            set {
                this.latitudFieldSpecified = value;
                this.RaisePropertyChanged("latitudSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
                this.RaisePropertyChanged("longitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool longitudSpecified {
            get {
                return this.longitudFieldSpecified;
            }
            set {
                this.longitudFieldSpecified = value;
                this.RaisePropertyChanged("longitudSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public usuarioDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contraseñaField;
        
        private string emailField;
        
        private estadoConexionDTO estadoConexionField;
        
        private bool estadoConexionFieldSpecified;
        
        private localDateTime fechaRegistroField;
        
        private int idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string nombreField;
        
        private rolUsuarioDTO rolField;
        
        private bool rolFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoConexionDTO estadoConexion {
            get {
                return this.estadoConexionField;
            }
            set {
                this.estadoConexionField = value;
                this.RaisePropertyChanged("estadoConexion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoConexionSpecified {
            get {
                return this.estadoConexionFieldSpecified;
            }
            set {
                this.estadoConexionFieldSpecified = value;
                this.RaisePropertyChanged("estadoConexionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public rolUsuarioDTO rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rolSpecified {
            get {
                return this.rolFieldSpecified;
            }
            set {
                this.rolFieldSpecified = value;
                this.RaisePropertyChanged("rolSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public enum estadoConexionDTO {
        
        /// <remarks/>
        CONECTADO,
        
        /// <remarks/>
        DESCONECTADO,
        
        /// <remarks/>
        EN_eSPERA,
        
        /// <remarks/>
        RECONECTADO,
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        LIMITADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class localDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public enum rolUsuarioDTO {
        
        /// <remarks/>
        CLIENTE,
        
        /// <remarks/>
        ADMINISTRADOR,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerLocalizacionPorId", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerLocalizacionPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idLocalizacion;
        
        public obtenerLocalizacionPorIdRequest() {
        }
        
        public obtenerLocalizacionPorIdRequest(int idLocalizacion) {
            this.idLocalizacion = idLocalizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerLocalizacionPorIdResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerLocalizacionPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperBO.LocalizacionesWS.localizacionDTO @return;
        
        public obtenerLocalizacionPorIdResponse() {
        }
        
        public obtenerLocalizacionPorIdResponse(TechShopperBO.LocalizacionesWS.localizacionDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarLocalizacion", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarLocalizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idLocalizacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public actualizarLocalizacionRequest() {
        }
        
        public actualizarLocalizacionRequest(int idLocalizacion, string direccion, int idUsuario) {
            this.idLocalizacion = idLocalizacion;
            this.direccion = direccion;
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarLocalizacionResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarLocalizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarLocalizacionResponse() {
        }
        
        public actualizarLocalizacionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarLocalizacion", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarLocalizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idLocalizacion;
        
        public eliminarLocalizacionRequest() {
        }
        
        public eliminarLocalizacionRequest(int idLocalizacion) {
            this.idLocalizacion = idLocalizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarLocalizacionResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarLocalizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarLocalizacionResponse() {
        }
        
        public eliminarLocalizacionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasLasLocalizaciones", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasLasLocalizacionesRequest {
        
        public listarTodasLasLocalizacionesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasLasLocalizacionesResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasLasLocalizacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperBO.LocalizacionesWS.localizacionDTO[] @return;
        
        public listarTodasLasLocalizacionesResponse() {
        }
        
        public listarTodasLasLocalizacionesResponse(TechShopperBO.LocalizacionesWS.localizacionDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LocalizacionesChannel : TechShopperBO.LocalizacionesWS.Localizaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocalizacionesClient : System.ServiceModel.ClientBase<TechShopperBO.LocalizacionesWS.Localizaciones>, TechShopperBO.LocalizacionesWS.Localizaciones {
        
        public LocalizacionesClient() {
        }
        
        public LocalizacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocalizacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalizacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalizacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.LocalizacionesWS.insertarLocalizacionResponse TechShopperBO.LocalizacionesWS.Localizaciones.insertarLocalizacion(TechShopperBO.LocalizacionesWS.insertarLocalizacionRequest request) {
            return base.Channel.insertarLocalizacion(request);
        }
        
        public int insertarLocalizacion(string direccion, double latitud, double longitud, int idUsuario) {
            TechShopperBO.LocalizacionesWS.insertarLocalizacionRequest inValue = new TechShopperBO.LocalizacionesWS.insertarLocalizacionRequest();
            inValue.direccion = direccion;
            inValue.latitud = latitud;
            inValue.longitud = longitud;
            inValue.idUsuario = idUsuario;
            TechShopperBO.LocalizacionesWS.insertarLocalizacionResponse retVal = ((TechShopperBO.LocalizacionesWS.Localizaciones)(this)).insertarLocalizacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.LocalizacionesWS.insertarLocalizacionResponse> TechShopperBO.LocalizacionesWS.Localizaciones.insertarLocalizacionAsync(TechShopperBO.LocalizacionesWS.insertarLocalizacionRequest request) {
            return base.Channel.insertarLocalizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.LocalizacionesWS.insertarLocalizacionResponse> insertarLocalizacionAsync(string direccion, double latitud, double longitud, int idUsuario) {
            TechShopperBO.LocalizacionesWS.insertarLocalizacionRequest inValue = new TechShopperBO.LocalizacionesWS.insertarLocalizacionRequest();
            inValue.direccion = direccion;
            inValue.latitud = latitud;
            inValue.longitud = longitud;
            inValue.idUsuario = idUsuario;
            return ((TechShopperBO.LocalizacionesWS.Localizaciones)(this)).insertarLocalizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.LocalizacionesWS.obtenerLocalizacionPorIdResponse TechShopperBO.LocalizacionesWS.Localizaciones.obtenerLocalizacionPorId(TechShopperBO.LocalizacionesWS.obtenerLocalizacionPorIdRequest request) {
            return base.Channel.obtenerLocalizacionPorId(request);
        }
        
        public TechShopperBO.LocalizacionesWS.localizacionDTO obtenerLocalizacionPorId(int idLocalizacion) {
            TechShopperBO.LocalizacionesWS.obtenerLocalizacionPorIdRequest inValue = new TechShopperBO.LocalizacionesWS.obtenerLocalizacionPorIdRequest();
            inValue.idLocalizacion = idLocalizacion;
            TechShopperBO.LocalizacionesWS.obtenerLocalizacionPorIdResponse retVal = ((TechShopperBO.LocalizacionesWS.Localizaciones)(this)).obtenerLocalizacionPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.LocalizacionesWS.obtenerLocalizacionPorIdResponse> TechShopperBO.LocalizacionesWS.Localizaciones.obtenerLocalizacionPorIdAsync(TechShopperBO.LocalizacionesWS.obtenerLocalizacionPorIdRequest request) {
            return base.Channel.obtenerLocalizacionPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.LocalizacionesWS.obtenerLocalizacionPorIdResponse> obtenerLocalizacionPorIdAsync(int idLocalizacion) {
            TechShopperBO.LocalizacionesWS.obtenerLocalizacionPorIdRequest inValue = new TechShopperBO.LocalizacionesWS.obtenerLocalizacionPorIdRequest();
            inValue.idLocalizacion = idLocalizacion;
            return ((TechShopperBO.LocalizacionesWS.Localizaciones)(this)).obtenerLocalizacionPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.LocalizacionesWS.actualizarLocalizacionResponse TechShopperBO.LocalizacionesWS.Localizaciones.actualizarLocalizacion(TechShopperBO.LocalizacionesWS.actualizarLocalizacionRequest request) {
            return base.Channel.actualizarLocalizacion(request);
        }
        
        public int actualizarLocalizacion(int idLocalizacion, string direccion, int idUsuario) {
            TechShopperBO.LocalizacionesWS.actualizarLocalizacionRequest inValue = new TechShopperBO.LocalizacionesWS.actualizarLocalizacionRequest();
            inValue.idLocalizacion = idLocalizacion;
            inValue.direccion = direccion;
            inValue.idUsuario = idUsuario;
            TechShopperBO.LocalizacionesWS.actualizarLocalizacionResponse retVal = ((TechShopperBO.LocalizacionesWS.Localizaciones)(this)).actualizarLocalizacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.LocalizacionesWS.actualizarLocalizacionResponse> TechShopperBO.LocalizacionesWS.Localizaciones.actualizarLocalizacionAsync(TechShopperBO.LocalizacionesWS.actualizarLocalizacionRequest request) {
            return base.Channel.actualizarLocalizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.LocalizacionesWS.actualizarLocalizacionResponse> actualizarLocalizacionAsync(int idLocalizacion, string direccion, int idUsuario) {
            TechShopperBO.LocalizacionesWS.actualizarLocalizacionRequest inValue = new TechShopperBO.LocalizacionesWS.actualizarLocalizacionRequest();
            inValue.idLocalizacion = idLocalizacion;
            inValue.direccion = direccion;
            inValue.idUsuario = idUsuario;
            return ((TechShopperBO.LocalizacionesWS.Localizaciones)(this)).actualizarLocalizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.LocalizacionesWS.eliminarLocalizacionResponse TechShopperBO.LocalizacionesWS.Localizaciones.eliminarLocalizacion(TechShopperBO.LocalizacionesWS.eliminarLocalizacionRequest request) {
            return base.Channel.eliminarLocalizacion(request);
        }
        
        public int eliminarLocalizacion(int idLocalizacion) {
            TechShopperBO.LocalizacionesWS.eliminarLocalizacionRequest inValue = new TechShopperBO.LocalizacionesWS.eliminarLocalizacionRequest();
            inValue.idLocalizacion = idLocalizacion;
            TechShopperBO.LocalizacionesWS.eliminarLocalizacionResponse retVal = ((TechShopperBO.LocalizacionesWS.Localizaciones)(this)).eliminarLocalizacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.LocalizacionesWS.eliminarLocalizacionResponse> TechShopperBO.LocalizacionesWS.Localizaciones.eliminarLocalizacionAsync(TechShopperBO.LocalizacionesWS.eliminarLocalizacionRequest request) {
            return base.Channel.eliminarLocalizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.LocalizacionesWS.eliminarLocalizacionResponse> eliminarLocalizacionAsync(int idLocalizacion) {
            TechShopperBO.LocalizacionesWS.eliminarLocalizacionRequest inValue = new TechShopperBO.LocalizacionesWS.eliminarLocalizacionRequest();
            inValue.idLocalizacion = idLocalizacion;
            return ((TechShopperBO.LocalizacionesWS.Localizaciones)(this)).eliminarLocalizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.LocalizacionesWS.listarTodasLasLocalizacionesResponse TechShopperBO.LocalizacionesWS.Localizaciones.listarTodasLasLocalizaciones(TechShopperBO.LocalizacionesWS.listarTodasLasLocalizacionesRequest request) {
            return base.Channel.listarTodasLasLocalizaciones(request);
        }
        
        public TechShopperBO.LocalizacionesWS.localizacionDTO[] listarTodasLasLocalizaciones() {
            TechShopperBO.LocalizacionesWS.listarTodasLasLocalizacionesRequest inValue = new TechShopperBO.LocalizacionesWS.listarTodasLasLocalizacionesRequest();
            TechShopperBO.LocalizacionesWS.listarTodasLasLocalizacionesResponse retVal = ((TechShopperBO.LocalizacionesWS.Localizaciones)(this)).listarTodasLasLocalizaciones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.LocalizacionesWS.listarTodasLasLocalizacionesResponse> TechShopperBO.LocalizacionesWS.Localizaciones.listarTodasLasLocalizacionesAsync(TechShopperBO.LocalizacionesWS.listarTodasLasLocalizacionesRequest request) {
            return base.Channel.listarTodasLasLocalizacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.LocalizacionesWS.listarTodasLasLocalizacionesResponse> listarTodasLasLocalizacionesAsync() {
            TechShopperBO.LocalizacionesWS.listarTodasLasLocalizacionesRequest inValue = new TechShopperBO.LocalizacionesWS.listarTodasLasLocalizacionesRequest();
            return ((TechShopperBO.LocalizacionesWS.Localizaciones)(this)).listarTodasLasLocalizacionesAsync(inValue);
        }
    }
}
