//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechShopperBO.MovimientosStockWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", ConfigurationName="MovimientosStockWS.MovimientosStock")]
    public interface MovimientosStock {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/MovimientosStock/eliminarMovimientoReques" +
            "t", ReplyAction="http://services.techshopper.pucp.edu.pe/MovimientosStock/eliminarMovimientoRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.MovimientosStockWS.eliminarMovimientoResponse eliminarMovimiento(TechShopperBO.MovimientosStockWS.eliminarMovimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/MovimientosStock/eliminarMovimientoReques" +
            "t", ReplyAction="http://services.techshopper.pucp.edu.pe/MovimientosStock/eliminarMovimientoRespon" +
            "se")]
        System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.eliminarMovimientoResponse> eliminarMovimientoAsync(TechShopperBO.MovimientosStockWS.eliminarMovimientoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/MovimientosStock/registrarMovimientoReque" +
            "st", ReplyAction="http://services.techshopper.pucp.edu.pe/MovimientosStock/registrarMovimientoRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.MovimientosStockWS.registrarMovimientoResponse registrarMovimiento(TechShopperBO.MovimientosStockWS.registrarMovimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/MovimientosStock/registrarMovimientoReque" +
            "st", ReplyAction="http://services.techshopper.pucp.edu.pe/MovimientosStock/registrarMovimientoRespo" +
            "nse")]
        System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.registrarMovimientoResponse> registrarMovimientoAsync(TechShopperBO.MovimientosStockWS.registrarMovimientoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/MovimientosStock/obtenerMovimientoPorIdRe" +
            "quest", ReplyAction="http://services.techshopper.pucp.edu.pe/MovimientosStock/obtenerMovimientoPorIdRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.MovimientosStockWS.obtenerMovimientoPorIdResponse obtenerMovimientoPorId(TechShopperBO.MovimientosStockWS.obtenerMovimientoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/MovimientosStock/obtenerMovimientoPorIdRe" +
            "quest", ReplyAction="http://services.techshopper.pucp.edu.pe/MovimientosStock/obtenerMovimientoPorIdRe" +
            "sponse")]
        System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.obtenerMovimientoPorIdResponse> obtenerMovimientoPorIdAsync(TechShopperBO.MovimientosStockWS.obtenerMovimientoPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/MovimientosStock/listarTodosLosMovimiento" +
            "sRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/MovimientosStock/listarTodosLosMovimiento" +
            "sResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.MovimientosStockWS.listarTodosLosMovimientosResponse listarTodosLosMovimientos(TechShopperBO.MovimientosStockWS.listarTodosLosMovimientosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/MovimientosStock/listarTodosLosMovimiento" +
            "sRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/MovimientosStock/listarTodosLosMovimiento" +
            "sResponse")]
        System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.listarTodosLosMovimientosResponse> listarTodosLosMovimientosAsync(TechShopperBO.MovimientosStockWS.listarTodosLosMovimientosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/MovimientosStock/registrarEntradaStockReq" +
            "uest", ReplyAction="http://services.techshopper.pucp.edu.pe/MovimientosStock/registrarEntradaStockRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.MovimientosStockWS.registrarEntradaStockResponse registrarEntradaStock(TechShopperBO.MovimientosStockWS.registrarEntradaStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/MovimientosStock/registrarEntradaStockReq" +
            "uest", ReplyAction="http://services.techshopper.pucp.edu.pe/MovimientosStock/registrarEntradaStockRes" +
            "ponse")]
        System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.registrarEntradaStockResponse> registrarEntradaStockAsync(TechShopperBO.MovimientosStockWS.registrarEntradaStockRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/MovimientosStock/registrarSalidaStockRequ" +
            "est", ReplyAction="http://services.techshopper.pucp.edu.pe/MovimientosStock/registrarSalidaStockResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.MovimientosStockWS.registrarSalidaStockResponse registrarSalidaStock(TechShopperBO.MovimientosStockWS.registrarSalidaStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/MovimientosStock/registrarSalidaStockRequ" +
            "est", ReplyAction="http://services.techshopper.pucp.edu.pe/MovimientosStock/registrarSalidaStockResp" +
            "onse")]
        System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.registrarSalidaStockResponse> registrarSalidaStockAsync(TechShopperBO.MovimientosStockWS.registrarSalidaStockRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/MovimientosStock/modificarMovimientoReque" +
            "st", ReplyAction="http://services.techshopper.pucp.edu.pe/MovimientosStock/modificarMovimientoRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.MovimientosStockWS.modificarMovimientoResponse modificarMovimiento(TechShopperBO.MovimientosStockWS.modificarMovimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/MovimientosStock/modificarMovimientoReque" +
            "st", ReplyAction="http://services.techshopper.pucp.edu.pe/MovimientosStock/modificarMovimientoRespo" +
            "nse")]
        System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.modificarMovimientoResponse> modificarMovimientoAsync(TechShopperBO.MovimientosStockWS.modificarMovimientoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/MovimientosStock/listarMovimientosPorProd" +
            "uctoRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/MovimientosStock/listarMovimientosPorProd" +
            "uctoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperBO.MovimientosStockWS.listarMovimientosPorProductoResponse listarMovimientosPorProducto(TechShopperBO.MovimientosStockWS.listarMovimientosPorProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/MovimientosStock/listarMovimientosPorProd" +
            "uctoRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/MovimientosStock/listarMovimientosPorProd" +
            "uctoResponse")]
        System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.listarMovimientosPorProductoResponse> listarMovimientosPorProductoAsync(TechShopperBO.MovimientosStockWS.listarMovimientosPorProductoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarMovimiento", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarMovimientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMovimiento;
        
        public eliminarMovimientoRequest() {
        }
        
        public eliminarMovimientoRequest(int idMovimiento) {
            this.idMovimiento = idMovimiento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarMovimientoResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarMovimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarMovimientoResponse() {
        }
        
        public eliminarMovimientoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class localDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contraseñaField;
        
        private string emailField;
        
        private estadoConexionDTO estadoConexionField;
        
        private bool estadoConexionFieldSpecified;
        
        private localDateTime fechaRegistroField;
        
        private int idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string nombreField;
        
        private rolUsuarioDTO rolField;
        
        private bool rolFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoConexionDTO estadoConexion {
            get {
                return this.estadoConexionField;
            }
            set {
                this.estadoConexionField = value;
                this.RaisePropertyChanged("estadoConexion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoConexionSpecified {
            get {
                return this.estadoConexionFieldSpecified;
            }
            set {
                this.estadoConexionFieldSpecified = value;
                this.RaisePropertyChanged("estadoConexionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public rolUsuarioDTO rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rolSpecified {
            get {
                return this.rolFieldSpecified;
            }
            set {
                this.rolFieldSpecified = value;
                this.RaisePropertyChanged("rolSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public enum estadoConexionDTO {
        
        /// <remarks/>
        CONECTADO,
        
        /// <remarks/>
        DESCONECTADO,
        
        /// <remarks/>
        EN_eSPERA,
        
        /// <remarks/>
        RECONECTADO,
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        LIMITADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public enum rolUsuarioDTO {
        
        /// <remarks/>
        CLIENTE,
        
        /// <remarks/>
        ADMINISTRADOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class productoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private categoriaDTO categoriaField;
        
        private bool categoriaFieldSpecified;
        
        private string descripcionField;
        
        private int idProductoField;
        
        private bool idProductoFieldSpecified;
        
        private string imagenURLField;
        
        private string marcaField;
        
        private string nombreField;
        
        private double precioField;
        
        private bool precioFieldSpecified;
        
        private int stockDisponibleField;
        
        private bool stockDisponibleFieldSpecified;
        
        private int stockMinimoField;
        
        private bool stockMinimoFieldSpecified;
        
        private int stockReservadoField;
        
        private bool stockReservadoFieldSpecified;
        
        private usuarioDTO usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaDTO categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaSpecified {
            get {
                return this.categoriaFieldSpecified;
            }
            set {
                this.categoriaFieldSpecified = value;
                this.RaisePropertyChanged("categoriaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoSpecified {
            get {
                return this.idProductoFieldSpecified;
            }
            set {
                this.idProductoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string imagenURL {
            get {
                return this.imagenURLField;
            }
            set {
                this.imagenURLField = value;
                this.RaisePropertyChanged("imagenURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioSpecified {
            get {
                return this.precioFieldSpecified;
            }
            set {
                this.precioFieldSpecified = value;
                this.RaisePropertyChanged("precioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int stockDisponible {
            get {
                return this.stockDisponibleField;
            }
            set {
                this.stockDisponibleField = value;
                this.RaisePropertyChanged("stockDisponible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockDisponibleSpecified {
            get {
                return this.stockDisponibleFieldSpecified;
            }
            set {
                this.stockDisponibleFieldSpecified = value;
                this.RaisePropertyChanged("stockDisponibleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int stockMinimo {
            get {
                return this.stockMinimoField;
            }
            set {
                this.stockMinimoField = value;
                this.RaisePropertyChanged("stockMinimo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockMinimoSpecified {
            get {
                return this.stockMinimoFieldSpecified;
            }
            set {
                this.stockMinimoFieldSpecified = value;
                this.RaisePropertyChanged("stockMinimoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int stockReservado {
            get {
                return this.stockReservadoField;
            }
            set {
                this.stockReservadoField = value;
                this.RaisePropertyChanged("stockReservado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockReservadoSpecified {
            get {
                return this.stockReservadoFieldSpecified;
            }
            set {
                this.stockReservadoFieldSpecified = value;
                this.RaisePropertyChanged("stockReservadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public usuarioDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public enum categoriaDTO {
        
        /// <remarks/>
        LAPTOP,
        
        /// <remarks/>
        PC,
        
        /// <remarks/>
        MOUSE,
        
        /// <remarks/>
        MONITOR,
        
        /// <remarks/>
        TECLADO,
        
        /// <remarks/>
        AURICULARES,
        
        /// <remarks/>
        AUDIFONOS,
        
        /// <remarks/>
        MICROFONO,
        
        /// <remarks/>
        PARLANTES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class movimientoStockDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private localDateTime fechaMovimientoField;
        
        private int idMovimientoField;
        
        private bool idMovimientoFieldSpecified;
        
        private productoDTO productoField;
        
        private tipoMovimientoDTO tipoField;
        
        private bool tipoFieldSpecified;
        
        private usuarioDTO usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
                this.RaisePropertyChanged("cantidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public localDateTime fechaMovimiento {
            get {
                return this.fechaMovimientoField;
            }
            set {
                this.fechaMovimientoField = value;
                this.RaisePropertyChanged("fechaMovimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idMovimiento {
            get {
                return this.idMovimientoField;
            }
            set {
                this.idMovimientoField = value;
                this.RaisePropertyChanged("idMovimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idMovimientoSpecified {
            get {
                return this.idMovimientoFieldSpecified;
            }
            set {
                this.idMovimientoFieldSpecified = value;
                this.RaisePropertyChanged("idMovimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public productoDTO producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public tipoMovimientoDTO tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public usuarioDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public enum tipoMovimientoDTO {
        
        /// <remarks/>
        ENTRADA,
        
        /// <remarks/>
        SALIDA,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarMovimiento", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class registrarMovimientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperBO.MovimientosStockWS.localDateTime fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public registrarMovimientoRequest() {
        }
        
        public registrarMovimientoRequest(int idProducto, string tipo, int cantidad, TechShopperBO.MovimientosStockWS.localDateTime fecha, int idUsuario) {
            this.idProducto = idProducto;
            this.tipo = tipo;
            this.cantidad = cantidad;
            this.fecha = fecha;
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarMovimientoResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class registrarMovimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public registrarMovimientoResponse() {
        }
        
        public registrarMovimientoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMovimientoPorId", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerMovimientoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMovimiento;
        
        public obtenerMovimientoPorIdRequest() {
        }
        
        public obtenerMovimientoPorIdRequest(int idMovimiento) {
            this.idMovimiento = idMovimiento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMovimientoPorIdResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerMovimientoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperBO.MovimientosStockWS.movimientoStockDTO @return;
        
        public obtenerMovimientoPorIdResponse() {
        }
        
        public obtenerMovimientoPorIdResponse(TechShopperBO.MovimientosStockWS.movimientoStockDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosLosMovimientos", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosLosMovimientosRequest {
        
        public listarTodosLosMovimientosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosLosMovimientosResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosLosMovimientosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperBO.MovimientosStockWS.movimientoStockDTO[] @return;
        
        public listarTodosLosMovimientosResponse() {
        }
        
        public listarTodosLosMovimientosResponse(TechShopperBO.MovimientosStockWS.movimientoStockDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarEntradaStock", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class registrarEntradaStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public registrarEntradaStockRequest() {
        }
        
        public registrarEntradaStockRequest(int idProducto, int cantidad, int idUsuario) {
            this.idProducto = idProducto;
            this.cantidad = cantidad;
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarEntradaStockResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class registrarEntradaStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public registrarEntradaStockResponse() {
        }
        
        public registrarEntradaStockResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarSalidaStock", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class registrarSalidaStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public registrarSalidaStockRequest() {
        }
        
        public registrarSalidaStockRequest(int idProducto, int cantidad, int idUsuario) {
            this.idProducto = idProducto;
            this.cantidad = cantidad;
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarSalidaStockResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class registrarSalidaStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public registrarSalidaStockResponse() {
        }
        
        public registrarSalidaStockResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarMovimiento", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarMovimientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMovimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperBO.MovimientosStockWS.localDateTime fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public modificarMovimientoRequest() {
        }
        
        public modificarMovimientoRequest(int idMovimiento, int idProducto, string tipo, int cantidad, TechShopperBO.MovimientosStockWS.localDateTime fecha, int idUsuario) {
            this.idMovimiento = idMovimiento;
            this.idProducto = idProducto;
            this.tipo = tipo;
            this.cantidad = cantidad;
            this.fecha = fecha;
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarMovimientoResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarMovimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarMovimientoResponse() {
        }
        
        public modificarMovimientoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMovimientosPorProducto", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarMovimientosPorProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        public listarMovimientosPorProductoRequest() {
        }
        
        public listarMovimientosPorProductoRequest(int idProducto) {
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMovimientosPorProductoResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarMovimientosPorProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperBO.MovimientosStockWS.movimientoStockDTO[] @return;
        
        public listarMovimientosPorProductoResponse() {
        }
        
        public listarMovimientosPorProductoResponse(TechShopperBO.MovimientosStockWS.movimientoStockDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MovimientosStockChannel : TechShopperBO.MovimientosStockWS.MovimientosStock, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovimientosStockClient : System.ServiceModel.ClientBase<TechShopperBO.MovimientosStockWS.MovimientosStock>, TechShopperBO.MovimientosStockWS.MovimientosStock {
        
        public MovimientosStockClient() {
        }
        
        public MovimientosStockClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovimientosStockClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovimientosStockClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovimientosStockClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.MovimientosStockWS.eliminarMovimientoResponse TechShopperBO.MovimientosStockWS.MovimientosStock.eliminarMovimiento(TechShopperBO.MovimientosStockWS.eliminarMovimientoRequest request) {
            return base.Channel.eliminarMovimiento(request);
        }
        
        public int eliminarMovimiento(int idMovimiento) {
            TechShopperBO.MovimientosStockWS.eliminarMovimientoRequest inValue = new TechShopperBO.MovimientosStockWS.eliminarMovimientoRequest();
            inValue.idMovimiento = idMovimiento;
            TechShopperBO.MovimientosStockWS.eliminarMovimientoResponse retVal = ((TechShopperBO.MovimientosStockWS.MovimientosStock)(this)).eliminarMovimiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.eliminarMovimientoResponse> TechShopperBO.MovimientosStockWS.MovimientosStock.eliminarMovimientoAsync(TechShopperBO.MovimientosStockWS.eliminarMovimientoRequest request) {
            return base.Channel.eliminarMovimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.eliminarMovimientoResponse> eliminarMovimientoAsync(int idMovimiento) {
            TechShopperBO.MovimientosStockWS.eliminarMovimientoRequest inValue = new TechShopperBO.MovimientosStockWS.eliminarMovimientoRequest();
            inValue.idMovimiento = idMovimiento;
            return ((TechShopperBO.MovimientosStockWS.MovimientosStock)(this)).eliminarMovimientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.MovimientosStockWS.registrarMovimientoResponse TechShopperBO.MovimientosStockWS.MovimientosStock.registrarMovimiento(TechShopperBO.MovimientosStockWS.registrarMovimientoRequest request) {
            return base.Channel.registrarMovimiento(request);
        }
        
        public int registrarMovimiento(int idProducto, string tipo, int cantidad, TechShopperBO.MovimientosStockWS.localDateTime fecha, int idUsuario) {
            TechShopperBO.MovimientosStockWS.registrarMovimientoRequest inValue = new TechShopperBO.MovimientosStockWS.registrarMovimientoRequest();
            inValue.idProducto = idProducto;
            inValue.tipo = tipo;
            inValue.cantidad = cantidad;
            inValue.fecha = fecha;
            inValue.idUsuario = idUsuario;
            TechShopperBO.MovimientosStockWS.registrarMovimientoResponse retVal = ((TechShopperBO.MovimientosStockWS.MovimientosStock)(this)).registrarMovimiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.registrarMovimientoResponse> TechShopperBO.MovimientosStockWS.MovimientosStock.registrarMovimientoAsync(TechShopperBO.MovimientosStockWS.registrarMovimientoRequest request) {
            return base.Channel.registrarMovimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.registrarMovimientoResponse> registrarMovimientoAsync(int idProducto, string tipo, int cantidad, TechShopperBO.MovimientosStockWS.localDateTime fecha, int idUsuario) {
            TechShopperBO.MovimientosStockWS.registrarMovimientoRequest inValue = new TechShopperBO.MovimientosStockWS.registrarMovimientoRequest();
            inValue.idProducto = idProducto;
            inValue.tipo = tipo;
            inValue.cantidad = cantidad;
            inValue.fecha = fecha;
            inValue.idUsuario = idUsuario;
            return ((TechShopperBO.MovimientosStockWS.MovimientosStock)(this)).registrarMovimientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.MovimientosStockWS.obtenerMovimientoPorIdResponse TechShopperBO.MovimientosStockWS.MovimientosStock.obtenerMovimientoPorId(TechShopperBO.MovimientosStockWS.obtenerMovimientoPorIdRequest request) {
            return base.Channel.obtenerMovimientoPorId(request);
        }
        
        public TechShopperBO.MovimientosStockWS.movimientoStockDTO obtenerMovimientoPorId(int idMovimiento) {
            TechShopperBO.MovimientosStockWS.obtenerMovimientoPorIdRequest inValue = new TechShopperBO.MovimientosStockWS.obtenerMovimientoPorIdRequest();
            inValue.idMovimiento = idMovimiento;
            TechShopperBO.MovimientosStockWS.obtenerMovimientoPorIdResponse retVal = ((TechShopperBO.MovimientosStockWS.MovimientosStock)(this)).obtenerMovimientoPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.obtenerMovimientoPorIdResponse> TechShopperBO.MovimientosStockWS.MovimientosStock.obtenerMovimientoPorIdAsync(TechShopperBO.MovimientosStockWS.obtenerMovimientoPorIdRequest request) {
            return base.Channel.obtenerMovimientoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.obtenerMovimientoPorIdResponse> obtenerMovimientoPorIdAsync(int idMovimiento) {
            TechShopperBO.MovimientosStockWS.obtenerMovimientoPorIdRequest inValue = new TechShopperBO.MovimientosStockWS.obtenerMovimientoPorIdRequest();
            inValue.idMovimiento = idMovimiento;
            return ((TechShopperBO.MovimientosStockWS.MovimientosStock)(this)).obtenerMovimientoPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.MovimientosStockWS.listarTodosLosMovimientosResponse TechShopperBO.MovimientosStockWS.MovimientosStock.listarTodosLosMovimientos(TechShopperBO.MovimientosStockWS.listarTodosLosMovimientosRequest request) {
            return base.Channel.listarTodosLosMovimientos(request);
        }
        
        public TechShopperBO.MovimientosStockWS.movimientoStockDTO[] listarTodosLosMovimientos() {
            TechShopperBO.MovimientosStockWS.listarTodosLosMovimientosRequest inValue = new TechShopperBO.MovimientosStockWS.listarTodosLosMovimientosRequest();
            TechShopperBO.MovimientosStockWS.listarTodosLosMovimientosResponse retVal = ((TechShopperBO.MovimientosStockWS.MovimientosStock)(this)).listarTodosLosMovimientos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.listarTodosLosMovimientosResponse> TechShopperBO.MovimientosStockWS.MovimientosStock.listarTodosLosMovimientosAsync(TechShopperBO.MovimientosStockWS.listarTodosLosMovimientosRequest request) {
            return base.Channel.listarTodosLosMovimientosAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.listarTodosLosMovimientosResponse> listarTodosLosMovimientosAsync() {
            TechShopperBO.MovimientosStockWS.listarTodosLosMovimientosRequest inValue = new TechShopperBO.MovimientosStockWS.listarTodosLosMovimientosRequest();
            return ((TechShopperBO.MovimientosStockWS.MovimientosStock)(this)).listarTodosLosMovimientosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.MovimientosStockWS.registrarEntradaStockResponse TechShopperBO.MovimientosStockWS.MovimientosStock.registrarEntradaStock(TechShopperBO.MovimientosStockWS.registrarEntradaStockRequest request) {
            return base.Channel.registrarEntradaStock(request);
        }
        
        public int registrarEntradaStock(int idProducto, int cantidad, int idUsuario) {
            TechShopperBO.MovimientosStockWS.registrarEntradaStockRequest inValue = new TechShopperBO.MovimientosStockWS.registrarEntradaStockRequest();
            inValue.idProducto = idProducto;
            inValue.cantidad = cantidad;
            inValue.idUsuario = idUsuario;
            TechShopperBO.MovimientosStockWS.registrarEntradaStockResponse retVal = ((TechShopperBO.MovimientosStockWS.MovimientosStock)(this)).registrarEntradaStock(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.registrarEntradaStockResponse> TechShopperBO.MovimientosStockWS.MovimientosStock.registrarEntradaStockAsync(TechShopperBO.MovimientosStockWS.registrarEntradaStockRequest request) {
            return base.Channel.registrarEntradaStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.registrarEntradaStockResponse> registrarEntradaStockAsync(int idProducto, int cantidad, int idUsuario) {
            TechShopperBO.MovimientosStockWS.registrarEntradaStockRequest inValue = new TechShopperBO.MovimientosStockWS.registrarEntradaStockRequest();
            inValue.idProducto = idProducto;
            inValue.cantidad = cantidad;
            inValue.idUsuario = idUsuario;
            return ((TechShopperBO.MovimientosStockWS.MovimientosStock)(this)).registrarEntradaStockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.MovimientosStockWS.registrarSalidaStockResponse TechShopperBO.MovimientosStockWS.MovimientosStock.registrarSalidaStock(TechShopperBO.MovimientosStockWS.registrarSalidaStockRequest request) {
            return base.Channel.registrarSalidaStock(request);
        }
        
        public int registrarSalidaStock(int idProducto, int cantidad, int idUsuario) {
            TechShopperBO.MovimientosStockWS.registrarSalidaStockRequest inValue = new TechShopperBO.MovimientosStockWS.registrarSalidaStockRequest();
            inValue.idProducto = idProducto;
            inValue.cantidad = cantidad;
            inValue.idUsuario = idUsuario;
            TechShopperBO.MovimientosStockWS.registrarSalidaStockResponse retVal = ((TechShopperBO.MovimientosStockWS.MovimientosStock)(this)).registrarSalidaStock(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.registrarSalidaStockResponse> TechShopperBO.MovimientosStockWS.MovimientosStock.registrarSalidaStockAsync(TechShopperBO.MovimientosStockWS.registrarSalidaStockRequest request) {
            return base.Channel.registrarSalidaStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.registrarSalidaStockResponse> registrarSalidaStockAsync(int idProducto, int cantidad, int idUsuario) {
            TechShopperBO.MovimientosStockWS.registrarSalidaStockRequest inValue = new TechShopperBO.MovimientosStockWS.registrarSalidaStockRequest();
            inValue.idProducto = idProducto;
            inValue.cantidad = cantidad;
            inValue.idUsuario = idUsuario;
            return ((TechShopperBO.MovimientosStockWS.MovimientosStock)(this)).registrarSalidaStockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.MovimientosStockWS.modificarMovimientoResponse TechShopperBO.MovimientosStockWS.MovimientosStock.modificarMovimiento(TechShopperBO.MovimientosStockWS.modificarMovimientoRequest request) {
            return base.Channel.modificarMovimiento(request);
        }
        
        public int modificarMovimiento(int idMovimiento, int idProducto, string tipo, int cantidad, TechShopperBO.MovimientosStockWS.localDateTime fecha, int idUsuario) {
            TechShopperBO.MovimientosStockWS.modificarMovimientoRequest inValue = new TechShopperBO.MovimientosStockWS.modificarMovimientoRequest();
            inValue.idMovimiento = idMovimiento;
            inValue.idProducto = idProducto;
            inValue.tipo = tipo;
            inValue.cantidad = cantidad;
            inValue.fecha = fecha;
            inValue.idUsuario = idUsuario;
            TechShopperBO.MovimientosStockWS.modificarMovimientoResponse retVal = ((TechShopperBO.MovimientosStockWS.MovimientosStock)(this)).modificarMovimiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.modificarMovimientoResponse> TechShopperBO.MovimientosStockWS.MovimientosStock.modificarMovimientoAsync(TechShopperBO.MovimientosStockWS.modificarMovimientoRequest request) {
            return base.Channel.modificarMovimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.modificarMovimientoResponse> modificarMovimientoAsync(int idMovimiento, int idProducto, string tipo, int cantidad, TechShopperBO.MovimientosStockWS.localDateTime fecha, int idUsuario) {
            TechShopperBO.MovimientosStockWS.modificarMovimientoRequest inValue = new TechShopperBO.MovimientosStockWS.modificarMovimientoRequest();
            inValue.idMovimiento = idMovimiento;
            inValue.idProducto = idProducto;
            inValue.tipo = tipo;
            inValue.cantidad = cantidad;
            inValue.fecha = fecha;
            inValue.idUsuario = idUsuario;
            return ((TechShopperBO.MovimientosStockWS.MovimientosStock)(this)).modificarMovimientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperBO.MovimientosStockWS.listarMovimientosPorProductoResponse TechShopperBO.MovimientosStockWS.MovimientosStock.listarMovimientosPorProducto(TechShopperBO.MovimientosStockWS.listarMovimientosPorProductoRequest request) {
            return base.Channel.listarMovimientosPorProducto(request);
        }
        
        public TechShopperBO.MovimientosStockWS.movimientoStockDTO[] listarMovimientosPorProducto(int idProducto) {
            TechShopperBO.MovimientosStockWS.listarMovimientosPorProductoRequest inValue = new TechShopperBO.MovimientosStockWS.listarMovimientosPorProductoRequest();
            inValue.idProducto = idProducto;
            TechShopperBO.MovimientosStockWS.listarMovimientosPorProductoResponse retVal = ((TechShopperBO.MovimientosStockWS.MovimientosStock)(this)).listarMovimientosPorProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.listarMovimientosPorProductoResponse> TechShopperBO.MovimientosStockWS.MovimientosStock.listarMovimientosPorProductoAsync(TechShopperBO.MovimientosStockWS.listarMovimientosPorProductoRequest request) {
            return base.Channel.listarMovimientosPorProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperBO.MovimientosStockWS.listarMovimientosPorProductoResponse> listarMovimientosPorProductoAsync(int idProducto) {
            TechShopperBO.MovimientosStockWS.listarMovimientosPorProductoRequest inValue = new TechShopperBO.MovimientosStockWS.listarMovimientosPorProductoRequest();
            inValue.idProducto = idProducto;
            return ((TechShopperBO.MovimientosStockWS.MovimientosStock)(this)).listarMovimientosPorProductoAsync(inValue);
        }
    }
}
