//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechShopperWA.AdministradoresWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", ConfigurationName="AdministradoresWS.Administradores")]
    public interface Administradores {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Administradores/iniciarSesionRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Administradores/iniciarSesionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.AdministradoresWS.iniciarSesionResponse iniciarSesion(TechShopperWA.AdministradoresWS.iniciarSesionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Administradores/iniciarSesionRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Administradores/iniciarSesionResponse")]
        System.Threading.Tasks.Task<TechShopperWA.AdministradoresWS.iniciarSesionResponse> iniciarSesionAsync(TechShopperWA.AdministradoresWS.iniciarSesionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Administradores/actualizarEstadoConexionR" +
            "equest", ReplyAction="http://services.techshopper.pucp.edu.pe/Administradores/actualizarEstadoConexionR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.AdministradoresWS.actualizarEstadoConexionResponse actualizarEstadoConexion(TechShopperWA.AdministradoresWS.actualizarEstadoConexionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Administradores/actualizarEstadoConexionR" +
            "equest", ReplyAction="http://services.techshopper.pucp.edu.pe/Administradores/actualizarEstadoConexionR" +
            "esponse")]
        System.Threading.Tasks.Task<TechShopperWA.AdministradoresWS.actualizarEstadoConexionResponse> actualizarEstadoConexionAsync(TechShopperWA.AdministradoresWS.actualizarEstadoConexionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Administradores/eliminarAdministradorRequ" +
            "est", ReplyAction="http://services.techshopper.pucp.edu.pe/Administradores/eliminarAdministradorResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.AdministradoresWS.eliminarAdministradorResponse eliminarAdministrador(TechShopperWA.AdministradoresWS.eliminarAdministradorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Administradores/eliminarAdministradorRequ" +
            "est", ReplyAction="http://services.techshopper.pucp.edu.pe/Administradores/eliminarAdministradorResp" +
            "onse")]
        System.Threading.Tasks.Task<TechShopperWA.AdministradoresWS.eliminarAdministradorResponse> eliminarAdministradorAsync(TechShopperWA.AdministradoresWS.eliminarAdministradorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Administradores/actualizarAdministradorRe" +
            "quest", ReplyAction="http://services.techshopper.pucp.edu.pe/Administradores/actualizarAdministradorRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.AdministradoresWS.actualizarAdministradorResponse actualizarAdministrador(TechShopperWA.AdministradoresWS.actualizarAdministradorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Administradores/actualizarAdministradorRe" +
            "quest", ReplyAction="http://services.techshopper.pucp.edu.pe/Administradores/actualizarAdministradorRe" +
            "sponse")]
        System.Threading.Tasks.Task<TechShopperWA.AdministradoresWS.actualizarAdministradorResponse> actualizarAdministradorAsync(TechShopperWA.AdministradoresWS.actualizarAdministradorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Administradores/registrarAdministradorReq" +
            "uest", ReplyAction="http://services.techshopper.pucp.edu.pe/Administradores/registrarAdministradorRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.AdministradoresWS.registrarAdministradorResponse registrarAdministrador(TechShopperWA.AdministradoresWS.registrarAdministradorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Administradores/registrarAdministradorReq" +
            "uest", ReplyAction="http://services.techshopper.pucp.edu.pe/Administradores/registrarAdministradorRes" +
            "ponse")]
        System.Threading.Tasks.Task<TechShopperWA.AdministradoresWS.registrarAdministradorResponse> registrarAdministradorAsync(TechShopperWA.AdministradoresWS.registrarAdministradorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Administradores/obtenerAdministradorPorId" +
            "Request", ReplyAction="http://services.techshopper.pucp.edu.pe/Administradores/obtenerAdministradorPorId" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.AdministradoresWS.obtenerAdministradorPorIdResponse obtenerAdministradorPorId(TechShopperWA.AdministradoresWS.obtenerAdministradorPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Administradores/obtenerAdministradorPorId" +
            "Request", ReplyAction="http://services.techshopper.pucp.edu.pe/Administradores/obtenerAdministradorPorId" +
            "Response")]
        System.Threading.Tasks.Task<TechShopperWA.AdministradoresWS.obtenerAdministradorPorIdResponse> obtenerAdministradorPorIdAsync(TechShopperWA.AdministradoresWS.obtenerAdministradorPorIdRequest request);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(administradorDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contraseñaField;
        
        private string emailField;
        
        private estadoConexionDTO estadoConexionField;
        
        private bool estadoConexionFieldSpecified;
        
        private localDateTime fechaRegistroField;
        
        private int idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string nombreField;
        
        private rolUsuarioDTO rolField;
        
        private bool rolFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoConexionDTO estadoConexion {
            get {
                return this.estadoConexionField;
            }
            set {
                this.estadoConexionField = value;
                this.RaisePropertyChanged("estadoConexion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoConexionSpecified {
            get {
                return this.estadoConexionFieldSpecified;
            }
            set {
                this.estadoConexionFieldSpecified = value;
                this.RaisePropertyChanged("estadoConexionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public rolUsuarioDTO rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rolSpecified {
            get {
                return this.rolFieldSpecified;
            }
            set {
                this.rolFieldSpecified = value;
                this.RaisePropertyChanged("rolSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public enum estadoConexionDTO {
        
        /// <remarks/>
        CONECTADO,
        
        /// <remarks/>
        DESCONECTADO,
        
        /// <remarks/>
        EN_eSPERA,
        
        /// <remarks/>
        RECONECTADO,
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        LIMITADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class localDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public enum rolUsuarioDTO {
        
        /// <remarks/>
        CLIENTE,
        
        /// <remarks/>
        ADMINISTRADOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class administradorDTO : usuarioDTO {
        
        private localDateTime fechaUltimoAccesoField;
        
        private nivelAccesoDTO nivelAccesoField;
        
        private bool nivelAccesoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public localDateTime fechaUltimoAcceso {
            get {
                return this.fechaUltimoAccesoField;
            }
            set {
                this.fechaUltimoAccesoField = value;
                this.RaisePropertyChanged("fechaUltimoAcceso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public nivelAccesoDTO nivelAcceso {
            get {
                return this.nivelAccesoField;
            }
            set {
                this.nivelAccesoField = value;
                this.RaisePropertyChanged("nivelAcceso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nivelAccesoSpecified {
            get {
                return this.nivelAccesoFieldSpecified;
            }
            set {
                this.nivelAccesoFieldSpecified = value;
                this.RaisePropertyChanged("nivelAccesoSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public enum nivelAccesoDTO {
        
        /// <remarks/>
        BASICO,
        
        /// <remarks/>
        MEDIO,
        
        /// <remarks/>
        AVANZADO,
        
        /// <remarks/>
        SUPER,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iniciarSesion", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class iniciarSesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correoONombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenia;
        
        public iniciarSesionRequest() {
        }
        
        public iniciarSesionRequest(string correoONombreUsuario, string contrasenia) {
            this.correoONombreUsuario = correoONombreUsuario;
            this.contrasenia = contrasenia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iniciarSesionResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class iniciarSesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperWA.AdministradoresWS.usuarioDTO @return;
        
        public iniciarSesionResponse() {
        }
        
        public iniciarSesionResponse(TechShopperWA.AdministradoresWS.usuarioDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEstadoConexion", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarEstadoConexionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAdministrador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nuevoEstado;
        
        public actualizarEstadoConexionRequest() {
        }
        
        public actualizarEstadoConexionRequest(int idAdministrador, string nuevoEstado) {
            this.idAdministrador = idAdministrador;
            this.nuevoEstado = nuevoEstado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEstadoConexionResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarEstadoConexionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarEstadoConexionResponse() {
        }
        
        public actualizarEstadoConexionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAdministrador", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarAdministradorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAdministrador;
        
        public eliminarAdministradorRequest() {
        }
        
        public eliminarAdministradorRequest(int idAdministrador) {
            this.idAdministrador = idAdministrador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAdministradorResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarAdministradorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarAdministradorResponse() {
        }
        
        public eliminarAdministradorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarAdministrador", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarAdministradorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAdministrador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contraseña;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estadoConexion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nivelAcceso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperWA.AdministradoresWS.localDateTime fechaRegistro;
        
        public actualizarAdministradorRequest() {
        }
        
        public actualizarAdministradorRequest(int idAdministrador, string contraseña, string estadoConexion, string nombre, string email, string nivelAcceso, TechShopperWA.AdministradoresWS.localDateTime fechaRegistro) {
            this.idAdministrador = idAdministrador;
            this.contraseña = contraseña;
            this.estadoConexion = estadoConexion;
            this.nombre = nombre;
            this.email = email;
            this.nivelAcceso = nivelAcceso;
            this.fechaRegistro = fechaRegistro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarAdministradorResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarAdministradorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarAdministradorResponse() {
        }
        
        public actualizarAdministradorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarAdministrador", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class registrarAdministradorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contraseña;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        public registrarAdministradorRequest() {
        }
        
        public registrarAdministradorRequest(string contraseña, string nombre, string email) {
            this.contraseña = contraseña;
            this.nombre = nombre;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarAdministradorResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class registrarAdministradorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public registrarAdministradorResponse() {
        }
        
        public registrarAdministradorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAdministradorPorId", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerAdministradorPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAdministrador;
        
        public obtenerAdministradorPorIdRequest() {
        }
        
        public obtenerAdministradorPorIdRequest(int idAdministrador) {
            this.idAdministrador = idAdministrador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAdministradorPorIdResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerAdministradorPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperWA.AdministradoresWS.administradorDTO @return;
        
        public obtenerAdministradorPorIdResponse() {
        }
        
        public obtenerAdministradorPorIdResponse(TechShopperWA.AdministradoresWS.administradorDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdministradoresChannel : TechShopperWA.AdministradoresWS.Administradores, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministradoresClient : System.ServiceModel.ClientBase<TechShopperWA.AdministradoresWS.Administradores>, TechShopperWA.AdministradoresWS.Administradores {
        
        public AdministradoresClient() {
        }
        
        public AdministradoresClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministradoresClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradoresClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradoresClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.AdministradoresWS.iniciarSesionResponse TechShopperWA.AdministradoresWS.Administradores.iniciarSesion(TechShopperWA.AdministradoresWS.iniciarSesionRequest request) {
            return base.Channel.iniciarSesion(request);
        }
        
        public TechShopperWA.AdministradoresWS.usuarioDTO iniciarSesion(string correoONombreUsuario, string contrasenia) {
            TechShopperWA.AdministradoresWS.iniciarSesionRequest inValue = new TechShopperWA.AdministradoresWS.iniciarSesionRequest();
            inValue.correoONombreUsuario = correoONombreUsuario;
            inValue.contrasenia = contrasenia;
            TechShopperWA.AdministradoresWS.iniciarSesionResponse retVal = ((TechShopperWA.AdministradoresWS.Administradores)(this)).iniciarSesion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.AdministradoresWS.iniciarSesionResponse> TechShopperWA.AdministradoresWS.Administradores.iniciarSesionAsync(TechShopperWA.AdministradoresWS.iniciarSesionRequest request) {
            return base.Channel.iniciarSesionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.AdministradoresWS.iniciarSesionResponse> iniciarSesionAsync(string correoONombreUsuario, string contrasenia) {
            TechShopperWA.AdministradoresWS.iniciarSesionRequest inValue = new TechShopperWA.AdministradoresWS.iniciarSesionRequest();
            inValue.correoONombreUsuario = correoONombreUsuario;
            inValue.contrasenia = contrasenia;
            return ((TechShopperWA.AdministradoresWS.Administradores)(this)).iniciarSesionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.AdministradoresWS.actualizarEstadoConexionResponse TechShopperWA.AdministradoresWS.Administradores.actualizarEstadoConexion(TechShopperWA.AdministradoresWS.actualizarEstadoConexionRequest request) {
            return base.Channel.actualizarEstadoConexion(request);
        }
        
        public int actualizarEstadoConexion(int idAdministrador, string nuevoEstado) {
            TechShopperWA.AdministradoresWS.actualizarEstadoConexionRequest inValue = new TechShopperWA.AdministradoresWS.actualizarEstadoConexionRequest();
            inValue.idAdministrador = idAdministrador;
            inValue.nuevoEstado = nuevoEstado;
            TechShopperWA.AdministradoresWS.actualizarEstadoConexionResponse retVal = ((TechShopperWA.AdministradoresWS.Administradores)(this)).actualizarEstadoConexion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.AdministradoresWS.actualizarEstadoConexionResponse> TechShopperWA.AdministradoresWS.Administradores.actualizarEstadoConexionAsync(TechShopperWA.AdministradoresWS.actualizarEstadoConexionRequest request) {
            return base.Channel.actualizarEstadoConexionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.AdministradoresWS.actualizarEstadoConexionResponse> actualizarEstadoConexionAsync(int idAdministrador, string nuevoEstado) {
            TechShopperWA.AdministradoresWS.actualizarEstadoConexionRequest inValue = new TechShopperWA.AdministradoresWS.actualizarEstadoConexionRequest();
            inValue.idAdministrador = idAdministrador;
            inValue.nuevoEstado = nuevoEstado;
            return ((TechShopperWA.AdministradoresWS.Administradores)(this)).actualizarEstadoConexionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.AdministradoresWS.eliminarAdministradorResponse TechShopperWA.AdministradoresWS.Administradores.eliminarAdministrador(TechShopperWA.AdministradoresWS.eliminarAdministradorRequest request) {
            return base.Channel.eliminarAdministrador(request);
        }
        
        public int eliminarAdministrador(int idAdministrador) {
            TechShopperWA.AdministradoresWS.eliminarAdministradorRequest inValue = new TechShopperWA.AdministradoresWS.eliminarAdministradorRequest();
            inValue.idAdministrador = idAdministrador;
            TechShopperWA.AdministradoresWS.eliminarAdministradorResponse retVal = ((TechShopperWA.AdministradoresWS.Administradores)(this)).eliminarAdministrador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.AdministradoresWS.eliminarAdministradorResponse> TechShopperWA.AdministradoresWS.Administradores.eliminarAdministradorAsync(TechShopperWA.AdministradoresWS.eliminarAdministradorRequest request) {
            return base.Channel.eliminarAdministradorAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.AdministradoresWS.eliminarAdministradorResponse> eliminarAdministradorAsync(int idAdministrador) {
            TechShopperWA.AdministradoresWS.eliminarAdministradorRequest inValue = new TechShopperWA.AdministradoresWS.eliminarAdministradorRequest();
            inValue.idAdministrador = idAdministrador;
            return ((TechShopperWA.AdministradoresWS.Administradores)(this)).eliminarAdministradorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.AdministradoresWS.actualizarAdministradorResponse TechShopperWA.AdministradoresWS.Administradores.actualizarAdministrador(TechShopperWA.AdministradoresWS.actualizarAdministradorRequest request) {
            return base.Channel.actualizarAdministrador(request);
        }
        
        public int actualizarAdministrador(int idAdministrador, string contraseña, string estadoConexion, string nombre, string email, string nivelAcceso, TechShopperWA.AdministradoresWS.localDateTime fechaRegistro) {
            TechShopperWA.AdministradoresWS.actualizarAdministradorRequest inValue = new TechShopperWA.AdministradoresWS.actualizarAdministradorRequest();
            inValue.idAdministrador = idAdministrador;
            inValue.contraseña = contraseña;
            inValue.estadoConexion = estadoConexion;
            inValue.nombre = nombre;
            inValue.email = email;
            inValue.nivelAcceso = nivelAcceso;
            inValue.fechaRegistro = fechaRegistro;
            TechShopperWA.AdministradoresWS.actualizarAdministradorResponse retVal = ((TechShopperWA.AdministradoresWS.Administradores)(this)).actualizarAdministrador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.AdministradoresWS.actualizarAdministradorResponse> TechShopperWA.AdministradoresWS.Administradores.actualizarAdministradorAsync(TechShopperWA.AdministradoresWS.actualizarAdministradorRequest request) {
            return base.Channel.actualizarAdministradorAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.AdministradoresWS.actualizarAdministradorResponse> actualizarAdministradorAsync(int idAdministrador, string contraseña, string estadoConexion, string nombre, string email, string nivelAcceso, TechShopperWA.AdministradoresWS.localDateTime fechaRegistro) {
            TechShopperWA.AdministradoresWS.actualizarAdministradorRequest inValue = new TechShopperWA.AdministradoresWS.actualizarAdministradorRequest();
            inValue.idAdministrador = idAdministrador;
            inValue.contraseña = contraseña;
            inValue.estadoConexion = estadoConexion;
            inValue.nombre = nombre;
            inValue.email = email;
            inValue.nivelAcceso = nivelAcceso;
            inValue.fechaRegistro = fechaRegistro;
            return ((TechShopperWA.AdministradoresWS.Administradores)(this)).actualizarAdministradorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.AdministradoresWS.registrarAdministradorResponse TechShopperWA.AdministradoresWS.Administradores.registrarAdministrador(TechShopperWA.AdministradoresWS.registrarAdministradorRequest request) {
            return base.Channel.registrarAdministrador(request);
        }
        
        public int registrarAdministrador(string contraseña, string nombre, string email) {
            TechShopperWA.AdministradoresWS.registrarAdministradorRequest inValue = new TechShopperWA.AdministradoresWS.registrarAdministradorRequest();
            inValue.contraseña = contraseña;
            inValue.nombre = nombre;
            inValue.email = email;
            TechShopperWA.AdministradoresWS.registrarAdministradorResponse retVal = ((TechShopperWA.AdministradoresWS.Administradores)(this)).registrarAdministrador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.AdministradoresWS.registrarAdministradorResponse> TechShopperWA.AdministradoresWS.Administradores.registrarAdministradorAsync(TechShopperWA.AdministradoresWS.registrarAdministradorRequest request) {
            return base.Channel.registrarAdministradorAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.AdministradoresWS.registrarAdministradorResponse> registrarAdministradorAsync(string contraseña, string nombre, string email) {
            TechShopperWA.AdministradoresWS.registrarAdministradorRequest inValue = new TechShopperWA.AdministradoresWS.registrarAdministradorRequest();
            inValue.contraseña = contraseña;
            inValue.nombre = nombre;
            inValue.email = email;
            return ((TechShopperWA.AdministradoresWS.Administradores)(this)).registrarAdministradorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.AdministradoresWS.obtenerAdministradorPorIdResponse TechShopperWA.AdministradoresWS.Administradores.obtenerAdministradorPorId(TechShopperWA.AdministradoresWS.obtenerAdministradorPorIdRequest request) {
            return base.Channel.obtenerAdministradorPorId(request);
        }
        
        public TechShopperWA.AdministradoresWS.administradorDTO obtenerAdministradorPorId(int idAdministrador) {
            TechShopperWA.AdministradoresWS.obtenerAdministradorPorIdRequest inValue = new TechShopperWA.AdministradoresWS.obtenerAdministradorPorIdRequest();
            inValue.idAdministrador = idAdministrador;
            TechShopperWA.AdministradoresWS.obtenerAdministradorPorIdResponse retVal = ((TechShopperWA.AdministradoresWS.Administradores)(this)).obtenerAdministradorPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.AdministradoresWS.obtenerAdministradorPorIdResponse> TechShopperWA.AdministradoresWS.Administradores.obtenerAdministradorPorIdAsync(TechShopperWA.AdministradoresWS.obtenerAdministradorPorIdRequest request) {
            return base.Channel.obtenerAdministradorPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.AdministradoresWS.obtenerAdministradorPorIdResponse> obtenerAdministradorPorIdAsync(int idAdministrador) {
            TechShopperWA.AdministradoresWS.obtenerAdministradorPorIdRequest inValue = new TechShopperWA.AdministradoresWS.obtenerAdministradorPorIdRequest();
            inValue.idAdministrador = idAdministrador;
            return ((TechShopperWA.AdministradoresWS.Administradores)(this)).obtenerAdministradorPorIdAsync(inValue);
        }
    }
}
