//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechShopperWA.ClientesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", ConfigurationName="ClientesWS.Clientes")]
    public interface Clientes {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/obtenerClientePorIdRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/obtenerClientePorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.ClientesWS.obtenerClientePorIdResponse obtenerClientePorId(TechShopperWA.ClientesWS.obtenerClientePorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/obtenerClientePorIdRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/obtenerClientePorIdResponse")]
        System.Threading.Tasks.Task<TechShopperWA.ClientesWS.obtenerClientePorIdResponse> obtenerClientePorIdAsync(TechShopperWA.ClientesWS.obtenerClientePorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/actualizarBalanceClienteRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/actualizarBalanceClienteResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.ClientesWS.actualizarBalanceClienteResponse actualizarBalanceCliente(TechShopperWA.ClientesWS.actualizarBalanceClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/actualizarBalanceClienteRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/actualizarBalanceClienteResponse" +
            "")]
        System.Threading.Tasks.Task<TechShopperWA.ClientesWS.actualizarBalanceClienteResponse> actualizarBalanceClienteAsync(TechShopperWA.ClientesWS.actualizarBalanceClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/actualizarClienteRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/actualizarClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.ClientesWS.actualizarClienteResponse actualizarCliente(TechShopperWA.ClientesWS.actualizarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/actualizarClienteRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/actualizarClienteResponse")]
        System.Threading.Tasks.Task<TechShopperWA.ClientesWS.actualizarClienteResponse> actualizarClienteAsync(TechShopperWA.ClientesWS.actualizarClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/registrarClienteRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/registrarClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.ClientesWS.registrarClienteResponse registrarCliente(TechShopperWA.ClientesWS.registrarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/registrarClienteRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/registrarClienteResponse")]
        System.Threading.Tasks.Task<TechShopperWA.ClientesWS.registrarClienteResponse> registrarClienteAsync(TechShopperWA.ClientesWS.registrarClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/eliminarClienteRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/eliminarClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.ClientesWS.eliminarClienteResponse eliminarCliente(TechShopperWA.ClientesWS.eliminarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/eliminarClienteRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/eliminarClienteResponse")]
        System.Threading.Tasks.Task<TechShopperWA.ClientesWS.eliminarClienteResponse> eliminarClienteAsync(TechShopperWA.ClientesWS.eliminarClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/listarClientesRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/listarClientesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.ClientesWS.listarClientesResponse listarClientes(TechShopperWA.ClientesWS.listarClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/listarClientesRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/listarClientesResponse")]
        System.Threading.Tasks.Task<TechShopperWA.ClientesWS.listarClientesResponse> listarClientesAsync(TechShopperWA.ClientesWS.listarClientesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/insertarCarritoRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/insertarCarritoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.ClientesWS.insertarCarritoResponse insertarCarrito(TechShopperWA.ClientesWS.insertarCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/insertarCarritoRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/insertarCarritoResponse")]
        System.Threading.Tasks.Task<TechShopperWA.ClientesWS.insertarCarritoResponse> insertarCarritoAsync(TechShopperWA.ClientesWS.insertarCarritoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/mostrarCarritoDeClienteRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/mostrarCarritoDeClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.ClientesWS.mostrarCarritoDeClienteResponse mostrarCarritoDeCliente(TechShopperWA.ClientesWS.mostrarCarritoDeClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/mostrarCarritoDeClienteRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/mostrarCarritoDeClienteResponse")]
        System.Threading.Tasks.Task<TechShopperWA.ClientesWS.mostrarCarritoDeClienteResponse> mostrarCarritoDeClienteAsync(TechShopperWA.ClientesWS.mostrarCarritoDeClienteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class clienteDTO : usuarioDTO {
        
        private double balanceCuentaField;
        
        private bool balanceCuentaFieldSpecified;
        
        private string direccionField;
        
        private string infoCompraField;
        
        private string infoTarjetaCreditoField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double balanceCuenta {
            get {
                return this.balanceCuentaField;
            }
            set {
                this.balanceCuentaField = value;
                this.RaisePropertyChanged("balanceCuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool balanceCuentaSpecified {
            get {
                return this.balanceCuentaFieldSpecified;
            }
            set {
                this.balanceCuentaFieldSpecified = value;
                this.RaisePropertyChanged("balanceCuentaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string infoCompra {
            get {
                return this.infoCompraField;
            }
            set {
                this.infoCompraField = value;
                this.RaisePropertyChanged("infoCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string infoTarjetaCredito {
            get {
                return this.infoTarjetaCreditoField;
            }
            set {
                this.infoTarjetaCreditoField = value;
                this.RaisePropertyChanged("infoTarjetaCredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clienteDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contraseñaField;
        
        private string emailField;
        
        private estadoConexionDTO estadoConexionField;
        
        private bool estadoConexionFieldSpecified;
        
        private localDateTime fechaRegistroField;
        
        private int idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string nombreField;
        
        private rolUsuarioDTO rolField;
        
        private bool rolFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoConexionDTO estadoConexion {
            get {
                return this.estadoConexionField;
            }
            set {
                this.estadoConexionField = value;
                this.RaisePropertyChanged("estadoConexion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoConexionSpecified {
            get {
                return this.estadoConexionFieldSpecified;
            }
            set {
                this.estadoConexionFieldSpecified = value;
                this.RaisePropertyChanged("estadoConexionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public rolUsuarioDTO rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rolSpecified {
            get {
                return this.rolFieldSpecified;
            }
            set {
                this.rolFieldSpecified = value;
                this.RaisePropertyChanged("rolSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public enum estadoConexionDTO {
        
        /// <remarks/>
        CONECTADO,
        
        /// <remarks/>
        DESCONECTADO,
        
        /// <remarks/>
        EN_eSPERA,
        
        /// <remarks/>
        RECONECTADO,
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        LIMITADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class localDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class productoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private categoriaDTO categoriaField;
        
        private bool categoriaFieldSpecified;
        
        private string descripcionField;
        
        private int idProductoField;
        
        private bool idProductoFieldSpecified;
        
        private string marcaField;
        
        private string nombreField;
        
        private double precioField;
        
        private bool precioFieldSpecified;
        
        private int stockDisponibleField;
        
        private bool stockDisponibleFieldSpecified;
        
        private int stockMinimoField;
        
        private bool stockMinimoFieldSpecified;
        
        private int stockReservadoField;
        
        private bool stockReservadoFieldSpecified;
        
        private usuarioDTO usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaDTO categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaSpecified {
            get {
                return this.categoriaFieldSpecified;
            }
            set {
                this.categoriaFieldSpecified = value;
                this.RaisePropertyChanged("categoriaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoSpecified {
            get {
                return this.idProductoFieldSpecified;
            }
            set {
                this.idProductoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioSpecified {
            get {
                return this.precioFieldSpecified;
            }
            set {
                this.precioFieldSpecified = value;
                this.RaisePropertyChanged("precioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int stockDisponible {
            get {
                return this.stockDisponibleField;
            }
            set {
                this.stockDisponibleField = value;
                this.RaisePropertyChanged("stockDisponible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockDisponibleSpecified {
            get {
                return this.stockDisponibleFieldSpecified;
            }
            set {
                this.stockDisponibleFieldSpecified = value;
                this.RaisePropertyChanged("stockDisponibleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int stockMinimo {
            get {
                return this.stockMinimoField;
            }
            set {
                this.stockMinimoField = value;
                this.RaisePropertyChanged("stockMinimo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockMinimoSpecified {
            get {
                return this.stockMinimoFieldSpecified;
            }
            set {
                this.stockMinimoFieldSpecified = value;
                this.RaisePropertyChanged("stockMinimoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int stockReservado {
            get {
                return this.stockReservadoField;
            }
            set {
                this.stockReservadoField = value;
                this.RaisePropertyChanged("stockReservado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockReservadoSpecified {
            get {
                return this.stockReservadoFieldSpecified;
            }
            set {
                this.stockReservadoFieldSpecified = value;
                this.RaisePropertyChanged("stockReservadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public usuarioDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public enum categoriaDTO {
        
        /// <remarks/>
        LAPTOP,
        
        /// <remarks/>
        PC,
        
        /// <remarks/>
        MOUSE,
        
        /// <remarks/>
        MONITOR,
        
        /// <remarks/>
        TECLADO,
        
        /// <remarks/>
        AURICULARES,
        
        /// <remarks/>
        AUDIFONOS,
        
        /// <remarks/>
        MICROFONO,
        
        /// <remarks/>
        PARLANTES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class carritoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idCarritoField;
        
        private bool idCarritoFieldSpecified;
        
        private double precioField;
        
        private bool precioFieldSpecified;
        
        private usuarioDTO usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idCarrito {
            get {
                return this.idCarritoField;
            }
            set {
                this.idCarritoField = value;
                this.RaisePropertyChanged("idCarrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCarritoSpecified {
            get {
                return this.idCarritoFieldSpecified;
            }
            set {
                this.idCarritoFieldSpecified = value;
                this.RaisePropertyChanged("idCarritoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioSpecified {
            get {
                return this.precioFieldSpecified;
            }
            set {
                this.precioFieldSpecified = value;
                this.RaisePropertyChanged("precioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public usuarioDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class carritoItemsDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private carritoDTO carritoField;
        
        private localDateTime fechaRegistroField;
        
        private double precioUnitarioField;
        
        private productoDTO productoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public carritoDTO carrito {
            get {
                return this.carritoField;
            }
            set {
                this.carritoField = value;
                this.RaisePropertyChanged("carrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public localDateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("precioUnitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public productoDTO producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public enum rolUsuarioDTO {
        
        /// <remarks/>
        CLIENTE,
        
        /// <remarks/>
        ADMINISTRADOR,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerClientePorId", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerClientePorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCliente;
        
        public obtenerClientePorIdRequest() {
        }
        
        public obtenerClientePorIdRequest(int idCliente) {
            this.idCliente = idCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerClientePorIdResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerClientePorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperWA.ClientesWS.clienteDTO @return;
        
        public obtenerClientePorIdResponse() {
        }
        
        public obtenerClientePorIdResponse(TechShopperWA.ClientesWS.clienteDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarBalanceCliente", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarBalanceClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double nuevoBalance;
        
        public actualizarBalanceClienteRequest() {
        }
        
        public actualizarBalanceClienteRequest(int idCliente, double nuevoBalance) {
            this.idCliente = idCliente;
            this.nuevoBalance = nuevoBalance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarBalanceClienteResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarBalanceClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarBalanceClienteResponse() {
        }
        
        public actualizarBalanceClienteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarCliente", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contraseña;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estadoConexion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string infoTarjetaCredito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double balanceCuenta;
        
        public actualizarClienteRequest() {
        }
        
        public actualizarClienteRequest(int idCliente, string contraseña, string estadoConexion, string nombre, string direccion, string telefono, string email, string infoTarjetaCredito, double balanceCuenta) {
            this.idCliente = idCliente;
            this.contraseña = contraseña;
            this.estadoConexion = estadoConexion;
            this.nombre = nombre;
            this.direccion = direccion;
            this.telefono = telefono;
            this.email = email;
            this.infoTarjetaCredito = infoTarjetaCredito;
            this.balanceCuenta = balanceCuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarClienteResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarClienteResponse() {
        }
        
        public actualizarClienteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarCliente", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class registrarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contraseña;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string infoTarjetaCredito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double balanceCuenta;
        
        public registrarClienteRequest() {
        }
        
        public registrarClienteRequest(string contraseña, string nombre, string email, string direccion, string telefono, string infoTarjetaCredito, double balanceCuenta) {
            this.contraseña = contraseña;
            this.nombre = nombre;
            this.email = email;
            this.direccion = direccion;
            this.telefono = telefono;
            this.infoTarjetaCredito = infoTarjetaCredito;
            this.balanceCuenta = balanceCuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarClienteResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class registrarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public registrarClienteResponse() {
        }
        
        public registrarClienteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCliente", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCliente;
        
        public eliminarClienteRequest() {
        }
        
        public eliminarClienteRequest(int idCliente) {
            this.idCliente = idCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarClienteResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarClienteResponse() {
        }
        
        public eliminarClienteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarClientes", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarClientesRequest {
        
        public listarClientesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarClientesResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperWA.ClientesWS.clienteDTO[] @return;
        
        public listarClientesResponse() {
        }
        
        public listarClientesResponse(TechShopperWA.ClientesWS.clienteDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCarrito", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        public insertarCarritoRequest() {
        }
        
        public insertarCarritoRequest(int idUsuario, int idProducto, int cantidad) {
            this.idUsuario = idUsuario;
            this.idProducto = idProducto;
            this.cantidad = cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCarritoResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarCarritoResponse() {
        }
        
        public insertarCarritoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostrarCarritoDeCliente", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class mostrarCarritoDeClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public mostrarCarritoDeClienteRequest() {
        }
        
        public mostrarCarritoDeClienteRequest(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostrarCarritoDeClienteResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class mostrarCarritoDeClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperWA.ClientesWS.carritoItemsDTO[] @return;
        
        public mostrarCarritoDeClienteResponse() {
        }
        
        public mostrarCarritoDeClienteResponse(TechShopperWA.ClientesWS.carritoItemsDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientesChannel : TechShopperWA.ClientesWS.Clientes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientesClient : System.ServiceModel.ClientBase<TechShopperWA.ClientesWS.Clientes>, TechShopperWA.ClientesWS.Clientes {
        
        public ClientesClient() {
        }
        
        public ClientesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.ClientesWS.obtenerClientePorIdResponse TechShopperWA.ClientesWS.Clientes.obtenerClientePorId(TechShopperWA.ClientesWS.obtenerClientePorIdRequest request) {
            return base.Channel.obtenerClientePorId(request);
        }
        
        public TechShopperWA.ClientesWS.clienteDTO obtenerClientePorId(int idCliente) {
            TechShopperWA.ClientesWS.obtenerClientePorIdRequest inValue = new TechShopperWA.ClientesWS.obtenerClientePorIdRequest();
            inValue.idCliente = idCliente;
            TechShopperWA.ClientesWS.obtenerClientePorIdResponse retVal = ((TechShopperWA.ClientesWS.Clientes)(this)).obtenerClientePorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.ClientesWS.obtenerClientePorIdResponse> TechShopperWA.ClientesWS.Clientes.obtenerClientePorIdAsync(TechShopperWA.ClientesWS.obtenerClientePorIdRequest request) {
            return base.Channel.obtenerClientePorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.ClientesWS.obtenerClientePorIdResponse> obtenerClientePorIdAsync(int idCliente) {
            TechShopperWA.ClientesWS.obtenerClientePorIdRequest inValue = new TechShopperWA.ClientesWS.obtenerClientePorIdRequest();
            inValue.idCliente = idCliente;
            return ((TechShopperWA.ClientesWS.Clientes)(this)).obtenerClientePorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.ClientesWS.actualizarBalanceClienteResponse TechShopperWA.ClientesWS.Clientes.actualizarBalanceCliente(TechShopperWA.ClientesWS.actualizarBalanceClienteRequest request) {
            return base.Channel.actualizarBalanceCliente(request);
        }
        
        public int actualizarBalanceCliente(int idCliente, double nuevoBalance) {
            TechShopperWA.ClientesWS.actualizarBalanceClienteRequest inValue = new TechShopperWA.ClientesWS.actualizarBalanceClienteRequest();
            inValue.idCliente = idCliente;
            inValue.nuevoBalance = nuevoBalance;
            TechShopperWA.ClientesWS.actualizarBalanceClienteResponse retVal = ((TechShopperWA.ClientesWS.Clientes)(this)).actualizarBalanceCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.ClientesWS.actualizarBalanceClienteResponse> TechShopperWA.ClientesWS.Clientes.actualizarBalanceClienteAsync(TechShopperWA.ClientesWS.actualizarBalanceClienteRequest request) {
            return base.Channel.actualizarBalanceClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.ClientesWS.actualizarBalanceClienteResponse> actualizarBalanceClienteAsync(int idCliente, double nuevoBalance) {
            TechShopperWA.ClientesWS.actualizarBalanceClienteRequest inValue = new TechShopperWA.ClientesWS.actualizarBalanceClienteRequest();
            inValue.idCliente = idCliente;
            inValue.nuevoBalance = nuevoBalance;
            return ((TechShopperWA.ClientesWS.Clientes)(this)).actualizarBalanceClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.ClientesWS.actualizarClienteResponse TechShopperWA.ClientesWS.Clientes.actualizarCliente(TechShopperWA.ClientesWS.actualizarClienteRequest request) {
            return base.Channel.actualizarCliente(request);
        }
        
        public int actualizarCliente(int idCliente, string contraseña, string estadoConexion, string nombre, string direccion, string telefono, string email, string infoTarjetaCredito, double balanceCuenta) {
            TechShopperWA.ClientesWS.actualizarClienteRequest inValue = new TechShopperWA.ClientesWS.actualizarClienteRequest();
            inValue.idCliente = idCliente;
            inValue.contraseña = contraseña;
            inValue.estadoConexion = estadoConexion;
            inValue.nombre = nombre;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.email = email;
            inValue.infoTarjetaCredito = infoTarjetaCredito;
            inValue.balanceCuenta = balanceCuenta;
            TechShopperWA.ClientesWS.actualizarClienteResponse retVal = ((TechShopperWA.ClientesWS.Clientes)(this)).actualizarCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.ClientesWS.actualizarClienteResponse> TechShopperWA.ClientesWS.Clientes.actualizarClienteAsync(TechShopperWA.ClientesWS.actualizarClienteRequest request) {
            return base.Channel.actualizarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.ClientesWS.actualizarClienteResponse> actualizarClienteAsync(int idCliente, string contraseña, string estadoConexion, string nombre, string direccion, string telefono, string email, string infoTarjetaCredito, double balanceCuenta) {
            TechShopperWA.ClientesWS.actualizarClienteRequest inValue = new TechShopperWA.ClientesWS.actualizarClienteRequest();
            inValue.idCliente = idCliente;
            inValue.contraseña = contraseña;
            inValue.estadoConexion = estadoConexion;
            inValue.nombre = nombre;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.email = email;
            inValue.infoTarjetaCredito = infoTarjetaCredito;
            inValue.balanceCuenta = balanceCuenta;
            return ((TechShopperWA.ClientesWS.Clientes)(this)).actualizarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.ClientesWS.registrarClienteResponse TechShopperWA.ClientesWS.Clientes.registrarCliente(TechShopperWA.ClientesWS.registrarClienteRequest request) {
            return base.Channel.registrarCliente(request);
        }
        
        public int registrarCliente(string contraseña, string nombre, string email, string direccion, string telefono, string infoTarjetaCredito, double balanceCuenta) {
            TechShopperWA.ClientesWS.registrarClienteRequest inValue = new TechShopperWA.ClientesWS.registrarClienteRequest();
            inValue.contraseña = contraseña;
            inValue.nombre = nombre;
            inValue.email = email;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.infoTarjetaCredito = infoTarjetaCredito;
            inValue.balanceCuenta = balanceCuenta;
            TechShopperWA.ClientesWS.registrarClienteResponse retVal = ((TechShopperWA.ClientesWS.Clientes)(this)).registrarCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.ClientesWS.registrarClienteResponse> TechShopperWA.ClientesWS.Clientes.registrarClienteAsync(TechShopperWA.ClientesWS.registrarClienteRequest request) {
            return base.Channel.registrarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.ClientesWS.registrarClienteResponse> registrarClienteAsync(string contraseña, string nombre, string email, string direccion, string telefono, string infoTarjetaCredito, double balanceCuenta) {
            TechShopperWA.ClientesWS.registrarClienteRequest inValue = new TechShopperWA.ClientesWS.registrarClienteRequest();
            inValue.contraseña = contraseña;
            inValue.nombre = nombre;
            inValue.email = email;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.infoTarjetaCredito = infoTarjetaCredito;
            inValue.balanceCuenta = balanceCuenta;
            return ((TechShopperWA.ClientesWS.Clientes)(this)).registrarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.ClientesWS.eliminarClienteResponse TechShopperWA.ClientesWS.Clientes.eliminarCliente(TechShopperWA.ClientesWS.eliminarClienteRequest request) {
            return base.Channel.eliminarCliente(request);
        }
        
        public int eliminarCliente(int idCliente) {
            TechShopperWA.ClientesWS.eliminarClienteRequest inValue = new TechShopperWA.ClientesWS.eliminarClienteRequest();
            inValue.idCliente = idCliente;
            TechShopperWA.ClientesWS.eliminarClienteResponse retVal = ((TechShopperWA.ClientesWS.Clientes)(this)).eliminarCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.ClientesWS.eliminarClienteResponse> TechShopperWA.ClientesWS.Clientes.eliminarClienteAsync(TechShopperWA.ClientesWS.eliminarClienteRequest request) {
            return base.Channel.eliminarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.ClientesWS.eliminarClienteResponse> eliminarClienteAsync(int idCliente) {
            TechShopperWA.ClientesWS.eliminarClienteRequest inValue = new TechShopperWA.ClientesWS.eliminarClienteRequest();
            inValue.idCliente = idCliente;
            return ((TechShopperWA.ClientesWS.Clientes)(this)).eliminarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.ClientesWS.listarClientesResponse TechShopperWA.ClientesWS.Clientes.listarClientes(TechShopperWA.ClientesWS.listarClientesRequest request) {
            return base.Channel.listarClientes(request);
        }
        
        public TechShopperWA.ClientesWS.clienteDTO[] listarClientes() {
            TechShopperWA.ClientesWS.listarClientesRequest inValue = new TechShopperWA.ClientesWS.listarClientesRequest();
            TechShopperWA.ClientesWS.listarClientesResponse retVal = ((TechShopperWA.ClientesWS.Clientes)(this)).listarClientes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.ClientesWS.listarClientesResponse> TechShopperWA.ClientesWS.Clientes.listarClientesAsync(TechShopperWA.ClientesWS.listarClientesRequest request) {
            return base.Channel.listarClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.ClientesWS.listarClientesResponse> listarClientesAsync() {
            TechShopperWA.ClientesWS.listarClientesRequest inValue = new TechShopperWA.ClientesWS.listarClientesRequest();
            return ((TechShopperWA.ClientesWS.Clientes)(this)).listarClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.ClientesWS.insertarCarritoResponse TechShopperWA.ClientesWS.Clientes.insertarCarrito(TechShopperWA.ClientesWS.insertarCarritoRequest request) {
            return base.Channel.insertarCarrito(request);
        }
        
        public int insertarCarrito(int idUsuario, int idProducto, int cantidad) {
            TechShopperWA.ClientesWS.insertarCarritoRequest inValue = new TechShopperWA.ClientesWS.insertarCarritoRequest();
            inValue.idUsuario = idUsuario;
            inValue.idProducto = idProducto;
            inValue.cantidad = cantidad;
            TechShopperWA.ClientesWS.insertarCarritoResponse retVal = ((TechShopperWA.ClientesWS.Clientes)(this)).insertarCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.ClientesWS.insertarCarritoResponse> TechShopperWA.ClientesWS.Clientes.insertarCarritoAsync(TechShopperWA.ClientesWS.insertarCarritoRequest request) {
            return base.Channel.insertarCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.ClientesWS.insertarCarritoResponse> insertarCarritoAsync(int idUsuario, int idProducto, int cantidad) {
            TechShopperWA.ClientesWS.insertarCarritoRequest inValue = new TechShopperWA.ClientesWS.insertarCarritoRequest();
            inValue.idUsuario = idUsuario;
            inValue.idProducto = idProducto;
            inValue.cantidad = cantidad;
            return ((TechShopperWA.ClientesWS.Clientes)(this)).insertarCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.ClientesWS.mostrarCarritoDeClienteResponse TechShopperWA.ClientesWS.Clientes.mostrarCarritoDeCliente(TechShopperWA.ClientesWS.mostrarCarritoDeClienteRequest request) {
            return base.Channel.mostrarCarritoDeCliente(request);
        }
        
        public TechShopperWA.ClientesWS.carritoItemsDTO[] mostrarCarritoDeCliente(int idUsuario) {
            TechShopperWA.ClientesWS.mostrarCarritoDeClienteRequest inValue = new TechShopperWA.ClientesWS.mostrarCarritoDeClienteRequest();
            inValue.idUsuario = idUsuario;
            TechShopperWA.ClientesWS.mostrarCarritoDeClienteResponse retVal = ((TechShopperWA.ClientesWS.Clientes)(this)).mostrarCarritoDeCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.ClientesWS.mostrarCarritoDeClienteResponse> TechShopperWA.ClientesWS.Clientes.mostrarCarritoDeClienteAsync(TechShopperWA.ClientesWS.mostrarCarritoDeClienteRequest request) {
            return base.Channel.mostrarCarritoDeClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.ClientesWS.mostrarCarritoDeClienteResponse> mostrarCarritoDeClienteAsync(int idUsuario) {
            TechShopperWA.ClientesWS.mostrarCarritoDeClienteRequest inValue = new TechShopperWA.ClientesWS.mostrarCarritoDeClienteRequest();
            inValue.idUsuario = idUsuario;
            return ((TechShopperWA.ClientesWS.Clientes)(this)).mostrarCarritoDeClienteAsync(inValue);
        }
    }
}
