//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechShopperWA.ReferenciaCliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", ConfigurationName="ReferenciaCliente.Clientes")]
    public interface Clientes {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/registrarClienteRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/registrarClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.ReferenciaCliente.registrarClienteResponse registrarCliente(TechShopperWA.ReferenciaCliente.registrarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/registrarClienteRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/registrarClienteResponse")]
        System.Threading.Tasks.Task<TechShopperWA.ReferenciaCliente.registrarClienteResponse> registrarClienteAsync(TechShopperWA.ReferenciaCliente.registrarClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/actualizarClienteRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/actualizarClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.ReferenciaCliente.actualizarClienteResponse actualizarCliente(TechShopperWA.ReferenciaCliente.actualizarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/actualizarClienteRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/actualizarClienteResponse")]
        System.Threading.Tasks.Task<TechShopperWA.ReferenciaCliente.actualizarClienteResponse> actualizarClienteAsync(TechShopperWA.ReferenciaCliente.actualizarClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/eliminarClienteRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/eliminarClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.ReferenciaCliente.eliminarClienteResponse eliminarCliente(TechShopperWA.ReferenciaCliente.eliminarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/eliminarClienteRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/eliminarClienteResponse")]
        System.Threading.Tasks.Task<TechShopperWA.ReferenciaCliente.eliminarClienteResponse> eliminarClienteAsync(TechShopperWA.ReferenciaCliente.eliminarClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/obtenerClientePorIdRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/obtenerClientePorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuarioDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.ReferenciaCliente.obtenerClientePorIdResponse obtenerClientePorId(TechShopperWA.ReferenciaCliente.obtenerClientePorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/obtenerClientePorIdRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/obtenerClientePorIdResponse")]
        System.Threading.Tasks.Task<TechShopperWA.ReferenciaCliente.obtenerClientePorIdResponse> obtenerClientePorIdAsync(TechShopperWA.ReferenciaCliente.obtenerClientePorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/actualizarEstadoConexionClienteR" +
            "equest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/actualizarEstadoConexionClienteR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuarioDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.ReferenciaCliente.actualizarEstadoConexionClienteResponse actualizarEstadoConexionCliente(TechShopperWA.ReferenciaCliente.actualizarEstadoConexionClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/actualizarEstadoConexionClienteR" +
            "equest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/actualizarEstadoConexionClienteR" +
            "esponse")]
        System.Threading.Tasks.Task<TechShopperWA.ReferenciaCliente.actualizarEstadoConexionClienteResponse> actualizarEstadoConexionClienteAsync(TechShopperWA.ReferenciaCliente.actualizarEstadoConexionClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/actualizarBalanceClienteRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/actualizarBalanceClienteResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuarioDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TechShopperWA.ReferenciaCliente.actualizarBalanceClienteResponse actualizarBalanceCliente(TechShopperWA.ReferenciaCliente.actualizarBalanceClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.techshopper.pucp.edu.pe/Clientes/actualizarBalanceClienteRequest", ReplyAction="http://services.techshopper.pucp.edu.pe/Clientes/actualizarBalanceClienteResponse" +
            "")]
        System.Threading.Tasks.Task<TechShopperWA.ReferenciaCliente.actualizarBalanceClienteResponse> actualizarBalanceClienteAsync(TechShopperWA.ReferenciaCliente.actualizarBalanceClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarCliente", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class registrarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contraseña;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string infoTarjetaCredito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double balanceCuenta;
        
        public registrarClienteRequest() {
        }
        
        public registrarClienteRequest(string contraseña, string nombre, string email, string direccion, string telefono, string infoTarjetaCredito, double balanceCuenta) {
            this.contraseña = contraseña;
            this.nombre = nombre;
            this.email = email;
            this.direccion = direccion;
            this.telefono = telefono;
            this.infoTarjetaCredito = infoTarjetaCredito;
            this.balanceCuenta = balanceCuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarClienteResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class registrarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public registrarClienteResponse() {
        }
        
        public registrarClienteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarCliente", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contraseña;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estadoConexion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string infoTarjetaCredito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double balanceCuenta;
        
        public actualizarClienteRequest() {
        }
        
        public actualizarClienteRequest(int idCliente, string contraseña, string estadoConexion, string nombre, string direccion, string telefono, string email, string infoTarjetaCredito, double balanceCuenta) {
            this.idCliente = idCliente;
            this.contraseña = contraseña;
            this.estadoConexion = estadoConexion;
            this.nombre = nombre;
            this.direccion = direccion;
            this.telefono = telefono;
            this.email = email;
            this.infoTarjetaCredito = infoTarjetaCredito;
            this.balanceCuenta = balanceCuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarClienteResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarClienteResponse() {
        }
        
        public actualizarClienteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCliente", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCliente;
        
        public eliminarClienteRequest() {
        }
        
        public eliminarClienteRequest(int idCliente) {
            this.idCliente = idCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarClienteResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarClienteResponse() {
        }
        
        public eliminarClienteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class clienteDTO : usuarioDTO {
        
        private double balanceCuentaField;
        
        private bool balanceCuentaFieldSpecified;
        
        private string direccionField;
        
        private string infoCompraField;
        
        private string infoTarjetaCreditoField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double balanceCuenta {
            get {
                return this.balanceCuentaField;
            }
            set {
                this.balanceCuentaField = value;
                this.RaisePropertyChanged("balanceCuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool balanceCuentaSpecified {
            get {
                return this.balanceCuentaFieldSpecified;
            }
            set {
                this.balanceCuentaFieldSpecified = value;
                this.RaisePropertyChanged("balanceCuentaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string infoCompra {
            get {
                return this.infoCompraField;
            }
            set {
                this.infoCompraField = value;
                this.RaisePropertyChanged("infoCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string infoTarjetaCredito {
            get {
                return this.infoTarjetaCreditoField;
            }
            set {
                this.infoTarjetaCreditoField = value;
                this.RaisePropertyChanged("infoTarjetaCredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clienteDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contraseñaField;
        
        private string emailField;
        
        private estadoConexionDTO estadoConexionField;
        
        private bool estadoConexionFieldSpecified;
        
        private localDateTime fechaRegistroField;
        
        private int idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string nombreField;
        
        private rolUsuarioDTO rolField;
        
        private bool rolFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoConexionDTO estadoConexion {
            get {
                return this.estadoConexionField;
            }
            set {
                this.estadoConexionField = value;
                this.RaisePropertyChanged("estadoConexion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoConexionSpecified {
            get {
                return this.estadoConexionFieldSpecified;
            }
            set {
                this.estadoConexionFieldSpecified = value;
                this.RaisePropertyChanged("estadoConexionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public rolUsuarioDTO rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rolSpecified {
            get {
                return this.rolFieldSpecified;
            }
            set {
                this.rolFieldSpecified = value;
                this.RaisePropertyChanged("rolSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public enum estadoConexionDTO {
        
        /// <remarks/>
        CONECTADO,
        
        /// <remarks/>
        DESCONECTADO,
        
        /// <remarks/>
        EN_eSPERA,
        
        /// <remarks/>
        RECONECTADO,
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        LIMITADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public partial class localDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.techshopper.pucp.edu.pe/")]
    public enum rolUsuarioDTO {
        
        /// <remarks/>
        CLIENTE,
        
        /// <remarks/>
        ADMINISTRADOR,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerClientePorId", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerClientePorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCliente;
        
        public obtenerClientePorIdRequest() {
        }
        
        public obtenerClientePorIdRequest(int idCliente) {
            this.idCliente = idCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerClientePorIdResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerClientePorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TechShopperWA.ReferenciaCliente.clienteDTO @return;
        
        public obtenerClientePorIdResponse() {
        }
        
        public obtenerClientePorIdResponse(TechShopperWA.ReferenciaCliente.clienteDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEstadoConexionCliente", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarEstadoConexionClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nuevoEstado;
        
        public actualizarEstadoConexionClienteRequest() {
        }
        
        public actualizarEstadoConexionClienteRequest(int idCliente, string nuevoEstado) {
            this.idCliente = idCliente;
            this.nuevoEstado = nuevoEstado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEstadoConexionClienteResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarEstadoConexionClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarEstadoConexionClienteResponse() {
        }
        
        public actualizarEstadoConexionClienteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarBalanceCliente", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarBalanceClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double nuevoBalance;
        
        public actualizarBalanceClienteRequest() {
        }
        
        public actualizarBalanceClienteRequest(int idCliente, double nuevoBalance) {
            this.idCliente = idCliente;
            this.nuevoBalance = nuevoBalance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarBalanceClienteResponse", WrapperNamespace="http://services.techshopper.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarBalanceClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.techshopper.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarBalanceClienteResponse() {
        }
        
        public actualizarBalanceClienteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientesChannel : TechShopperWA.ReferenciaCliente.Clientes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientesClient : System.ServiceModel.ClientBase<TechShopperWA.ReferenciaCliente.Clientes>, TechShopperWA.ReferenciaCliente.Clientes {
        
        public ClientesClient() {
        }
        
        public ClientesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.ReferenciaCliente.registrarClienteResponse TechShopperWA.ReferenciaCliente.Clientes.registrarCliente(TechShopperWA.ReferenciaCliente.registrarClienteRequest request) {
            return base.Channel.registrarCliente(request);
        }
        
        public int registrarCliente(string contraseña, string nombre, string email, string direccion, string telefono, string infoTarjetaCredito, double balanceCuenta) {
            TechShopperWA.ReferenciaCliente.registrarClienteRequest inValue = new TechShopperWA.ReferenciaCliente.registrarClienteRequest();
            inValue.contraseña = contraseña;
            inValue.nombre = nombre;
            inValue.email = email;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.infoTarjetaCredito = infoTarjetaCredito;
            inValue.balanceCuenta = balanceCuenta;
            TechShopperWA.ReferenciaCliente.registrarClienteResponse retVal = ((TechShopperWA.ReferenciaCliente.Clientes)(this)).registrarCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.ReferenciaCliente.registrarClienteResponse> TechShopperWA.ReferenciaCliente.Clientes.registrarClienteAsync(TechShopperWA.ReferenciaCliente.registrarClienteRequest request) {
            return base.Channel.registrarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.ReferenciaCliente.registrarClienteResponse> registrarClienteAsync(string contraseña, string nombre, string email, string direccion, string telefono, string infoTarjetaCredito, double balanceCuenta) {
            TechShopperWA.ReferenciaCliente.registrarClienteRequest inValue = new TechShopperWA.ReferenciaCliente.registrarClienteRequest();
            inValue.contraseña = contraseña;
            inValue.nombre = nombre;
            inValue.email = email;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.infoTarjetaCredito = infoTarjetaCredito;
            inValue.balanceCuenta = balanceCuenta;
            return ((TechShopperWA.ReferenciaCliente.Clientes)(this)).registrarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.ReferenciaCliente.actualizarClienteResponse TechShopperWA.ReferenciaCliente.Clientes.actualizarCliente(TechShopperWA.ReferenciaCliente.actualizarClienteRequest request) {
            return base.Channel.actualizarCliente(request);
        }
        
        public int actualizarCliente(int idCliente, string contraseña, string estadoConexion, string nombre, string direccion, string telefono, string email, string infoTarjetaCredito, double balanceCuenta) {
            TechShopperWA.ReferenciaCliente.actualizarClienteRequest inValue = new TechShopperWA.ReferenciaCliente.actualizarClienteRequest();
            inValue.idCliente = idCliente;
            inValue.contraseña = contraseña;
            inValue.estadoConexion = estadoConexion;
            inValue.nombre = nombre;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.email = email;
            inValue.infoTarjetaCredito = infoTarjetaCredito;
            inValue.balanceCuenta = balanceCuenta;
            TechShopperWA.ReferenciaCliente.actualizarClienteResponse retVal = ((TechShopperWA.ReferenciaCliente.Clientes)(this)).actualizarCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.ReferenciaCliente.actualizarClienteResponse> TechShopperWA.ReferenciaCliente.Clientes.actualizarClienteAsync(TechShopperWA.ReferenciaCliente.actualizarClienteRequest request) {
            return base.Channel.actualizarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.ReferenciaCliente.actualizarClienteResponse> actualizarClienteAsync(int idCliente, string contraseña, string estadoConexion, string nombre, string direccion, string telefono, string email, string infoTarjetaCredito, double balanceCuenta) {
            TechShopperWA.ReferenciaCliente.actualizarClienteRequest inValue = new TechShopperWA.ReferenciaCliente.actualizarClienteRequest();
            inValue.idCliente = idCliente;
            inValue.contraseña = contraseña;
            inValue.estadoConexion = estadoConexion;
            inValue.nombre = nombre;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.email = email;
            inValue.infoTarjetaCredito = infoTarjetaCredito;
            inValue.balanceCuenta = balanceCuenta;
            return ((TechShopperWA.ReferenciaCliente.Clientes)(this)).actualizarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.ReferenciaCliente.eliminarClienteResponse TechShopperWA.ReferenciaCliente.Clientes.eliminarCliente(TechShopperWA.ReferenciaCliente.eliminarClienteRequest request) {
            return base.Channel.eliminarCliente(request);
        }
        
        public int eliminarCliente(int idCliente) {
            TechShopperWA.ReferenciaCliente.eliminarClienteRequest inValue = new TechShopperWA.ReferenciaCliente.eliminarClienteRequest();
            inValue.idCliente = idCliente;
            TechShopperWA.ReferenciaCliente.eliminarClienteResponse retVal = ((TechShopperWA.ReferenciaCliente.Clientes)(this)).eliminarCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.ReferenciaCliente.eliminarClienteResponse> TechShopperWA.ReferenciaCliente.Clientes.eliminarClienteAsync(TechShopperWA.ReferenciaCliente.eliminarClienteRequest request) {
            return base.Channel.eliminarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.ReferenciaCliente.eliminarClienteResponse> eliminarClienteAsync(int idCliente) {
            TechShopperWA.ReferenciaCliente.eliminarClienteRequest inValue = new TechShopperWA.ReferenciaCliente.eliminarClienteRequest();
            inValue.idCliente = idCliente;
            return ((TechShopperWA.ReferenciaCliente.Clientes)(this)).eliminarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.ReferenciaCliente.obtenerClientePorIdResponse TechShopperWA.ReferenciaCliente.Clientes.obtenerClientePorId(TechShopperWA.ReferenciaCliente.obtenerClientePorIdRequest request) {
            return base.Channel.obtenerClientePorId(request);
        }
        
        public TechShopperWA.ReferenciaCliente.clienteDTO obtenerClientePorId(int idCliente) {
            TechShopperWA.ReferenciaCliente.obtenerClientePorIdRequest inValue = new TechShopperWA.ReferenciaCliente.obtenerClientePorIdRequest();
            inValue.idCliente = idCliente;
            TechShopperWA.ReferenciaCliente.obtenerClientePorIdResponse retVal = ((TechShopperWA.ReferenciaCliente.Clientes)(this)).obtenerClientePorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.ReferenciaCliente.obtenerClientePorIdResponse> TechShopperWA.ReferenciaCliente.Clientes.obtenerClientePorIdAsync(TechShopperWA.ReferenciaCliente.obtenerClientePorIdRequest request) {
            return base.Channel.obtenerClientePorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.ReferenciaCliente.obtenerClientePorIdResponse> obtenerClientePorIdAsync(int idCliente) {
            TechShopperWA.ReferenciaCliente.obtenerClientePorIdRequest inValue = new TechShopperWA.ReferenciaCliente.obtenerClientePorIdRequest();
            inValue.idCliente = idCliente;
            return ((TechShopperWA.ReferenciaCliente.Clientes)(this)).obtenerClientePorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.ReferenciaCliente.actualizarEstadoConexionClienteResponse TechShopperWA.ReferenciaCliente.Clientes.actualizarEstadoConexionCliente(TechShopperWA.ReferenciaCliente.actualizarEstadoConexionClienteRequest request) {
            return base.Channel.actualizarEstadoConexionCliente(request);
        }
        
        public int actualizarEstadoConexionCliente(int idCliente, string nuevoEstado) {
            TechShopperWA.ReferenciaCliente.actualizarEstadoConexionClienteRequest inValue = new TechShopperWA.ReferenciaCliente.actualizarEstadoConexionClienteRequest();
            inValue.idCliente = idCliente;
            inValue.nuevoEstado = nuevoEstado;
            TechShopperWA.ReferenciaCliente.actualizarEstadoConexionClienteResponse retVal = ((TechShopperWA.ReferenciaCliente.Clientes)(this)).actualizarEstadoConexionCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.ReferenciaCliente.actualizarEstadoConexionClienteResponse> TechShopperWA.ReferenciaCliente.Clientes.actualizarEstadoConexionClienteAsync(TechShopperWA.ReferenciaCliente.actualizarEstadoConexionClienteRequest request) {
            return base.Channel.actualizarEstadoConexionClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.ReferenciaCliente.actualizarEstadoConexionClienteResponse> actualizarEstadoConexionClienteAsync(int idCliente, string nuevoEstado) {
            TechShopperWA.ReferenciaCliente.actualizarEstadoConexionClienteRequest inValue = new TechShopperWA.ReferenciaCliente.actualizarEstadoConexionClienteRequest();
            inValue.idCliente = idCliente;
            inValue.nuevoEstado = nuevoEstado;
            return ((TechShopperWA.ReferenciaCliente.Clientes)(this)).actualizarEstadoConexionClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechShopperWA.ReferenciaCliente.actualizarBalanceClienteResponse TechShopperWA.ReferenciaCliente.Clientes.actualizarBalanceCliente(TechShopperWA.ReferenciaCliente.actualizarBalanceClienteRequest request) {
            return base.Channel.actualizarBalanceCliente(request);
        }
        
        public int actualizarBalanceCliente(int idCliente, double nuevoBalance) {
            TechShopperWA.ReferenciaCliente.actualizarBalanceClienteRequest inValue = new TechShopperWA.ReferenciaCliente.actualizarBalanceClienteRequest();
            inValue.idCliente = idCliente;
            inValue.nuevoBalance = nuevoBalance;
            TechShopperWA.ReferenciaCliente.actualizarBalanceClienteResponse retVal = ((TechShopperWA.ReferenciaCliente.Clientes)(this)).actualizarBalanceCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechShopperWA.ReferenciaCliente.actualizarBalanceClienteResponse> TechShopperWA.ReferenciaCliente.Clientes.actualizarBalanceClienteAsync(TechShopperWA.ReferenciaCliente.actualizarBalanceClienteRequest request) {
            return base.Channel.actualizarBalanceClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechShopperWA.ReferenciaCliente.actualizarBalanceClienteResponse> actualizarBalanceClienteAsync(int idCliente, double nuevoBalance) {
            TechShopperWA.ReferenciaCliente.actualizarBalanceClienteRequest inValue = new TechShopperWA.ReferenciaCliente.actualizarBalanceClienteRequest();
            inValue.idCliente = idCliente;
            inValue.nuevoBalance = nuevoBalance;
            return ((TechShopperWA.ReferenciaCliente.Clientes)(this)).actualizarBalanceClienteAsync(inValue);
        }
    }
}
